In [2]:
import pandas as pd
import numpy as np

In [3]:
Data = pd.read_csv('House_Price_Regression.csv')

Data['type'] = np.random.uniform(low=0, high=3, size=len(Data)).round()

Data['rating'] = np.random.uniform(low=0, high=5, size=len(Data)).round()

Data.head()

neighborhood_recode   latitude  longitude    price  no_of_bedrooms  \
0                 46.0  25.113208  55.138932  2700000               1   
1                 46.0  25.106809  55.151201  2850000               2   
2                 36.0  25.063302  55.137728  1150000               3   
3                 11.0  25.227295  55.341761  2850000               2   
4                 46.0  25.114275  55.139764  1729200               0   

   no_of_bathrooms  quality_recode  maid_room_recode  unfurnished_recode  \
0                2             2.0               0.0                 0.0   
1                2             2.0               0.0                 0.0   
2                5             2.0               1.0                 1.0   
3                3             1.0               0.0                 1.0   
4                1             2.0               0.0                 0.0   

   balcony_recode  ...  private_jacuzzi_recode  private_pool_recode  \
0             1.0  ...                     0.0                  0.0   
1             1.0  ...                     0.0                  0.0   
2             1.0  ...                     1.0                  0.0   
3             1.0  ...                     0.0                  0.0   
4             0.0  ...                     0.0                  0.0   

   security_recode  shared_gym_recode  shared_pool_recode  shared_spa_recode  \
0              0.0                1.0                 0.0                0.0   
1              0.0                1.0                 1.0                0.0   
2              1.0                1.0                 1.0                0.0   
3              0.0                0.0                 0.0                0.0   
4              1.0                1.0                 1.0                1.0   

   view_of_water_recode  size_in_m_2  type  rating  
0                   1.0   100.242337   2.0     1.0  
1                   1.0   146.972546   2.0     4.0  
2                   1.0   181.253753   1.0     4.0  
3                   0.0   187.664060   2.0     3.0  
4                   1.0    47.101821   1.0     1.0  

[5 rows x 31 columns]

In [6]:
Data_quant = Data.loc[: , ['latitude', 'longitude', 'price', 'size_in_m_2', 'no_of_bedrooms', 'no_of_bathrooms']]

In [33]:
Data_quant.head()

latitude  longitude    price  size_in_m_2  no_of_bedrooms  no_of_bathrooms
0  25.113208  55.138932  2700000   100.242337               1                2
1  25.106809  55.151201  2850000   146.972546               2                2
2  25.063302  55.137728  1150000   181.253753               3                5
3  25.227295  55.341761  2850000   187.664060               2                3
4  25.114275  55.139764  1729200    47.101821               0                1

In [7]:
Data_binary = Data.loc[: , ['private_garden_recode', 'private_gym_recode', 'private_jacuzzi_recode', 'balcony_recode']]

Data_binary.head()

private_garden_recode  private_gym_recode  private_jacuzzi_recode  \
0                    0.0                 0.0                     0.0   
1                    0.0                 0.0                     0.0   
2                    0.0                 0.0                     1.0   
3                    0.0                 0.0                     0.0   
4                    0.0                 0.0                     0.0   

   balcony_recode  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             0.0

In [8]:
Data_multiclass = Data.loc[: , ['quality_recode', 'rating', 'type']]

Data_multiclass.head()

quality_recode  rating  type
0             2.0     1.0   2.0
1             2.0     4.0   2.0
2             2.0     4.0   1.0
3             1.0     3.0   2.0
4             2.0     1.0   1.0

In [9]:
Data_mixed = Data.loc[: , ['latitude', 'longitude', 'price', 'size_in_m_2', 'no_of_bedrooms', 'no_of_bathrooms','private_garden_recode', 'private_gym_recode', 'private_jacuzzi_recode', 'balcony_recode','quality_recode', 'rating', 'type']]

Data_mixed.head()

latitude  longitude    price  size_in_m_2  no_of_bedrooms  \
0  25.113208  55.138932  2700000   100.242337               1   
1  25.106809  55.151201  2850000   146.972546               2   
2  25.063302  55.137728  1150000   181.253753               3   
3  25.227295  55.341761  2850000   187.664060               2   
4  25.114275  55.139764  1729200    47.101821               0   

   no_of_bathrooms  private_garden_recode  private_gym_recode  \
0                2                    0.0                 0.0   
1                2                    0.0                 0.0   
2                5                    0.0                 0.0   
3                3                    0.0                 0.0   
4                1                    0.0                 0.0   

   private_jacuzzi_recode  balcony_recode  quality_recode  rating  type  
0                     0.0             1.0             2.0     1.0   2.0  
1                     0.0             1.0             2.0     4.0   2.0  
2                     1.0             1.0             2.0     4.0   1.0  
3                     0.0             1.0             1.0     3.0   2.0  
4                     0.0             0.0             2.0     1.0   1.0

In [10]:
Data_quant_numpy = Data_quant.to_numpy()
Data_binary_numpy = Data_binary.to_numpy()
Data_multiclass_numpy = Data_multiclass.to_numpy()
Data_mixed_numpy = Data_mixed.to_numpy()

## Distancia Euclidea

In [37]:
def Dist_Euclidea(x_i, x_r):

        Dist_Euclidea = ( ( x_i - x_r )**2 ).sum()

        Dist_Euclidea = np.sqrt(Dist_Euclidea)

        return Dist_Euclidea

In [38]:
Dist_Euclidea(Data_quant.iloc[2,:] , Data_quant.iloc[5,:])

1969900.0019225744

In [40]:
def Matrix_Dist_Euclidea(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Euclidea(Data[i,:] , Data[r,:])   

                      
    return M 

In [41]:
M_Euclidean = Matrix_Dist_Euclidea(Data=Data_quant_numpy)

In [42]:
M_Euclidean

array([[      0.        ,  150000.00728238, 1550000.00212124, ...,
         200000.01565902, 2025000.00024491, 1939113.00017324],
       [      0.        ,       0.        , 1700000.00034859, ...,
          50000.01055292, 2175000.00140691, 2089113.00126347],
       [      0.        ,       0.        ,       0.        , ...,
        1750000.00000111,  475000.01333737,  389113.0147095 ],
       ...,
       [      0.        ,       0.        ,       0.        , ...,
              0.        , 2225000.00274952, 2139113.00257909],
       [      0.        ,       0.        ,       0.        , ...,
              0.        ,       0.        ,   85887.00018092],
       [      0.        ,       0.        ,       0.        , ...,
              0.        ,       0.        ,       0.        ]])

In [43]:
M_Euclidean = M_Euclidean + M_Euclidean.T

M_Euclidean

array([[      0.        ,  150000.00728238, 1550000.00212124, ...,
         200000.01565902, 2025000.00024491, 1939113.00017324],
       [ 150000.00728238,       0.        , 1700000.00034859, ...,
          50000.01055292, 2175000.00140691, 2089113.00126347],
       [1550000.00212124, 1700000.00034859,       0.        , ...,
        1750000.00000111,  475000.01333737,  389113.0147095 ],
       ...,
       [ 200000.01565902,   50000.01055292, 1750000.00000111, ...,
              0.        , 2225000.00274952, 2139113.00257909],
       [2025000.00024491, 2175000.00140691,  475000.01333737, ...,
        2225000.00274952,       0.        ,   85887.00018092],
       [1939113.00017324, 2089113.00126347,  389113.0147095 , ...,
        2139113.00257909,   85887.00018092,       0.        ]])

## Distancia de Minkowski

In [44]:
def Dist_Minkowski(x_i, x_r, q):

    Dist_Minkowski = ( ( ( abs( x_i - x_r) )**q ).sum() )**(1/q)

    return Dist_Minkowski

In [45]:
Dist_Minkowski(Data_quant.iloc[2,:], Data_quant.iloc[5,:], q=1)

1969992.0102169998

In [46]:
Dist_Minkowski(Data_quant.iloc[2,:], Data_quant.iloc[5,:], q=2)

1969900.0019225744

In [47]:
Dist_Minkowski(Data_quant.iloc[2,:], Data_quant.iloc[5,:], q=3)

1969900.000000055

In [48]:
Dist_Minkowski(Data_quant.iloc[2,:], Data_quant.iloc[5,:], q=10)

1969900.0000000016

In [49]:
def Matrix_Dist_Minkowski(Data, q):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Minkowski(Data[i,:] , Data[r,:], q)   

                      
    return M 

In [52]:
M_Minkowski = Matrix_Dist_Minkowski(Data=Data_quant_numpy , q=1)

M_Minkowski

array([[      0.      ,  150047.748877, 1550086.062526, ...,
         200084.359869, 2025031.624379, 1939138.969796],
       [      0.      ,       0.      , 1700038.338187, ...,
          50036.62379 , 2175079.33592 , 2089186.681337],
       [      0.      ,       0.      ,       0.      , ...,
        1750002.301489,  475117.608205,  389224.964166],
       ...,
       [      0.      ,       0.      ,       0.      , ...,
              0.      , 2225115.802424, 2139223.298103],
       [      0.      ,       0.      ,       0.      , ...,
              0.      ,       0.      ,   85892.654583],
       [      0.      ,       0.      ,       0.      , ...,
              0.      ,       0.      ,       0.      ]])

In [53]:
M_Minkowski = M_Minkowski + M_Minkowski.T

M_Minkowski

array([[      0.      ,  150047.748877, 1550086.062526, ...,
         200084.359869, 2025031.624379, 1939138.969796],
       [ 150047.748877,       0.      , 1700038.338187, ...,
          50036.62379 , 2175079.33592 , 2089186.681337],
       [1550086.062526, 1700038.338187,       0.      , ...,
        1750002.301489,  475117.608205,  389224.964166],
       ...,
       [ 200084.359869,   50036.62379 , 1750002.301489, ...,
              0.      , 2225115.802424, 2139223.298103],
       [2025031.624379, 2175079.33592 ,  475117.608205, ...,
        2225115.802424,       0.      ,   85892.654583],
       [1939138.969796, 2089186.681337,  389224.964166, ...,
        2139223.298103,   85892.654583,       0.      ]])

## Distancia Canberra

In [54]:
def Dist_Canberra(x_i, x_r):

    numerator =  abs( x_i - x_r )

    denominator =  ( abs(x_i) + abs(x_r) )
       
    numerator=np.array([numerator], dtype=float)

    denominator=np.array([denominator], dtype=float)

    # The following code is to eliminate zero division problems

    Dist_Canberra = ( np.divide( numerator , denominator , out=np.zeros_like(numerator), where=denominator!=0) ).sum() 

    return Dist_Canberra

In [55]:
Dist_Canberra(Data.iloc[2,:] , Data.iloc[5,:])

9.161812529108834

In [56]:
def Matrix_Dist_Canberra(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Canberra(Data[i,:] , Data[r,:])   

                      
    return M 

In [59]:
M_Canberra = Matrix_Dist_Canberra(Data=Data_quant_numpy)

M_Canberra

array([[0.        , 0.5496257 , 1.61996314, ..., 1.25082356, 0.78797391,
        0.70959891],
       [0.        , 0.        , 1.15900459, ..., 0.74009173, 1.31434216,
        1.24077176],
       [0.        , 0.        , 0.        , ..., 0.44223489, 1.63990915,
        1.55106392],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.00032192,
        1.93106183],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.09956138],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [60]:
M_Canberra = M_Canberra + M_Canberra.T

M_Canberra

array([[0.        , 0.5496257 , 1.61996314, ..., 1.25082356, 0.78797391,
        0.70959891],
       [0.5496257 , 0.        , 1.15900459, ..., 0.74009173, 1.31434216,
        1.24077176],
       [1.61996314, 1.15900459, 0.        , ..., 0.44223489, 1.63990915,
        1.55106392],
       ...,
       [1.25082356, 0.74009173, 0.44223489, ..., 0.        , 2.00032192,
        1.93106183],
       [0.78797391, 1.31434216, 1.63990915, ..., 2.00032192, 0.        ,
        0.09956138],
       [0.70959891, 1.24077176, 1.55106392, ..., 1.93106183, 0.09956138,
        0.        ]])

## Distancia Pearson

In [61]:
def Dist_Pearson(x_i, x_r, Data) :

    # Si Data  es un pd.DataFrame --> hay que convertilos antes a numpy con Data.to_numpy()

    Dist_Pearson = ( ( x_i - x_r )**2 / np.var(Data , axis=0, ddof=1) ).sum()

    # np.var(Data , axis=0, ddof=1)  calcula la cuasi-varianza (ddof=1) por columnas (axis=0)

    Dist_Pearson = np.sqrt(Dist_Pearson)

    return Dist_Pearson

In [62]:
Dist_Pearson(x_i=Data_quant_numpy[2,:], x_r=Data_quant_numpy[5,:], Data=Data_quant_numpy)

3.8239347754243425

In [63]:
def Matrix_Dist_Pearson(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Pearson(Data[i,:] , Data[r,:], Data=Data)   

                      
    return M 

In [64]:
M_Pearson = Matrix_Dist_Pearson(Data=Data_quant_numpy)

M_Pearson

array([[0.        , 1.21345279, 3.77819153, ..., 4.95085256, 1.66393723,
        0.94314867],
       [0.        , 0.        , 3.17880538, ..., 4.43821303, 2.03523139,
        1.60958264],
       [0.        , 0.        , 0.        , ..., 3.82999056, 4.01162596,
        3.76955491],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 4.69603617,
        5.13174853],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.09780835],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [65]:
M_Pearson = M_Pearson + M_Pearson.T

M_Pearson

array([[0.        , 1.21345279, 3.77819153, ..., 4.95085256, 1.66393723,
        0.94314867],
       [1.21345279, 0.        , 3.17880538, ..., 4.43821303, 2.03523139,
        1.60958264],
       [3.77819153, 3.17880538, 0.        , ..., 3.82999056, 4.01162596,
        3.76955491],
       ...,
       [4.95085256, 4.43821303, 3.82999056, ..., 0.        , 4.69603617,
        5.13174853],
       [1.66393723, 2.03523139, 4.01162596, ..., 4.69603617, 0.        ,
        1.09780835],
       [0.94314867, 1.60958264, 3.76955491, ..., 5.13174853, 1.09780835,
        0.        ]])

## Distancia de Mahalanobis

In [44]:
def Dist_Mahalanobis_1(x_i, x_r, Data):

    # All the columns of Data must be type = 'float' or 'int' (specially not 'object'), in other case we will find 
    # dimensional problems when Python compute   x @ S_inv @ x.T

    x = (x_i - x_r)

    x = np.array([x]) # necessary step to transpose a 1D array

    S_inv = np.linalg.inv( np.cov(Data , rowvar=False) ) # inverse of covariance matrix

    Dist_Maha = np.sqrt( x @ S_inv @ x.T )  # x @ S_inv @ x.T = np.matmul( np.matmul(x , S_inv) , x.T )

    Dist_Maha = float(Dist_Maha)

    return Dist_Maha

In [45]:
Dist_Mahalanobis_1(Data_quant_numpy[2,:] , Data_quant_numpy[5,:] , Data=Data_quant_numpy )

3.931396144771864

In [46]:
def Dist_Mahalanobis_2(x_i, x_r, S_inv):  # Más eficiente que la anterior

    # All the columns of Data must be type = 'float' or 'int' (specially not 'object'), in other case we will find 
    # dimensional problems when Python compute   x @ S_inv @ x.T

    x = (x_i - x_r)

    x = np.array([x]) # necessary step to transpose a 1D array

    Dist_Maha = np.sqrt( x @ S_inv @ x.T )  # x @ S_inv @ x.T = np.matmul( np.matmul(x , S_inv) , x.T )

    Dist_Maha = float(Dist_Maha)

    return Dist_Maha

In [47]:
Dist_Mahalanobis_2(x_i = Data_quant_numpy[2,:] , x_r = Data_quant_numpy[5,:] , S_inv = np.linalg.inv( np.cov(Data_quant_numpy , rowvar=False) ) )

3.931396144771864

In [48]:
def Dist_Mahalanobis_3(x, S_inv):  # Más eficiente que la anterior

    # All the columns of Data must be type = 'float' or 'int' (specially not 'object'), in other case we will find 
    # dimensional problems when Python compute   x @ S_inv @ x.T

    # x = (x_i - x_r)

    # x = np.array([x]) # necessary step to transpose a 1D array

    Dist_Maha = np.sqrt( x @ S_inv @ x.T )  # x @ S_inv @ x.T = np.matmul( np.matmul(x , S_inv) , x.T )

    Dist_Maha = float(Dist_Maha)

    return Dist_Maha

In [49]:
Dist_Mahalanobis_3(x = np.array([Data_quant_numpy[2,:] - Data_quant_numpy[5,:]]) , S_inv=np.linalg.inv( np.cov(Data_quant_numpy , rowvar=False) ))

3.931396144771864

In [50]:
def Matrix_Dist_Mahalanobis_1(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Mahalanobis_1(x_i = Data[i,:] , x_r = Data[r,:] , Data=Data )

                      
    return M 

In [68]:
Matrix_Dist_Mahalanobis_1(Data=Data_quant_numpy[0:1000 , 0:1000]) # 2.25 mins

array([[0.        , 2.16321817, 3.81131086, ..., 2.74083537, 3.84799958,
        1.06041471],
       [0.        , 0.        , 4.29953104, ..., 2.76698155, 2.78100414,
        2.20791581],
       [0.        , 0.        , 0.        , ..., 2.63546884, 4.34269664,
        3.32469143],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.18534065,
        1.8408748 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.09496075],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [73]:
Matrix_Dist_Mahalanobis_1(Data=Data_quant_numpy) # 8.52 mins

array([[0.        , 2.11289055, 3.7975463 , ..., 4.51559865, 2.31688444,
        1.10588047],
       [0.        , 0.        , 4.35615967, ..., 4.93340427, 2.74011739,
        2.12938584],
       [0.        , 0.        , 0.        , ..., 3.17779509, 3.49432487,
        3.23723317],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 3.58695453,
        4.11275247],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.46894947],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [61]:
def Matrix_Dist_Mahalanobis_2(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    S_inv = np.linalg.inv( np.cov(Data , rowvar=False) )

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Mahalanobis_2(x_i = Data[i,:] , x_r = Data[r,:] , S_inv = S_inv  )

                      
    return M 

In [69]:
Matrix_Dist_Mahalanobis_2(Data=Data_quant_numpy[0:1000 , 0:1000]) # 6.8 seg

array([[0.        , 2.16321817, 3.81131086, ..., 2.74083537, 3.84799958,
        1.06041471],
       [0.        , 0.        , 4.29953104, ..., 2.76698155, 2.78100414,
        2.20791581],
       [0.        , 0.        , 0.        , ..., 2.63546884, 4.34269664,
        3.32469143],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.18534065,
        1.8408748 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.09496075],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [72]:
Matrix_Dist_Mahalanobis_2(Data=Data_quant_numpy) # 22.5 seg

array([[0.        , 2.11289055, 3.7975463 , ..., 4.51559865, 2.31688444,
        1.10588047],
       [0.        , 0.        , 4.35615967, ..., 4.93340427, 2.74011739,
        2.12938584],
       [0.        , 0.        , 0.        , ..., 3.17779509, 3.49432487,
        3.23723317],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 3.58695453,
        4.11275247],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.46894947],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [46]:
def Matrix_Dist_Mahalanobis_3(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    S_inv=np.linalg.inv( np.cov(Data , rowvar=False) )

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Mahalanobis_3(x = np.array([Data[i,:] - Data[r,:]]) , S_inv=S_inv ) 

                      
    return M 

In [70]:
Matrix_Dist_Mahalanobis_3(Data=Data_quant_numpy[0:1000 , 0:1000]) # 4.8 seg

array([[0.        , 2.16321817, 3.81131086, ..., 2.74083537, 3.84799958,
        1.06041471],
       [0.        , 0.        , 4.29953104, ..., 2.76698155, 2.78100414,
        2.20791581],
       [0.        , 0.        , 0.        , ..., 2.63546884, 4.34269664,
        3.32469143],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.18534065,
        1.8408748 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.09496075],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [49]:
M_Mahalanobis = Matrix_Dist_Mahalanobis_3(Data=Data_quant_numpy) # 19.7 seg

M_Mahalanobis

array([[0.        , 2.11289055, 3.7975463 , ..., 4.51559865, 2.31688444,
        1.10588047],
       [0.        , 0.        , 4.35615967, ..., 4.93340427, 2.74011739,
        2.12938584],
       [0.        , 0.        , 0.        , ..., 3.17779509, 3.49432487,
        3.23723317],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 3.58695453,
        4.11275247],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.46894947],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [51]:
M_Mahalanobis = M_Mahalanobis + M_Mahalanobis.T

M_Mahalanobis

array([[0.        , 4.2257811 , 7.5950926 , ..., 9.03119731, 4.63376888,
        2.21176094],
       [4.2257811 , 0.        , 8.71231935, ..., 9.86680854, 5.48023478,
        4.25877168],
       [7.5950926 , 8.71231935, 0.        , ..., 6.35559018, 6.98864973,
        6.47446634],
       ...,
       [9.03119731, 9.86680854, 6.35559018, ..., 0.        , 7.17390906,
        8.22550494],
       [4.63376888, 5.48023478, 6.98864973, ..., 7.17390906, 0.        ,
        2.93789894],
       [2.21176094, 4.25877168, 6.47446634, ..., 8.22550494, 2.93789894,
        0.        ]])

In [10]:
def a_b_c_d_Matrix(Data):

    X = Data

    a = X @ X.T

    n = X.shape[0]

    p = X.shape[1]

    ones_matrix = np.ones((n, p)) 

    b = (ones_matrix - X) @ X.T

    c = b.T

    d = (ones_matrix - X) @ (ones_matrix - X).T

    return a , b , c , d , p

In [142]:
a, b, c, d, p = a_b_c_d_Matrix(Data_binary_numpy)

In [129]:
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 2., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 2., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [105]:
Data_binary_numpy[[30,1903], :]

array([[0., 1., 0., 1.],
       [1., 0., 0., 1.]])

In [103]:
a[30 , 1903]

1.0

In [113]:
Data_binary_numpy[[40,1903], :]

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [114]:
a[40 , 1903]

1.0

In [79]:
b

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.]])

In [106]:
Data_binary_numpy[[30,1903], :]

array([[0., 1., 0., 1.],
       [1., 0., 0., 1.]])

In [107]:
b[30 , 1903]

1.0

In [117]:
Data_binary_numpy[[40,1903], :]

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [118]:
b[40,1903]

1.0

In [80]:
c

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [108]:
c[30, 1903]

1.0

In [120]:
Data_binary_numpy[[40,1903], :]

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [119]:
c[40, 1903]

0.0

In [81]:
d

array([[3., 3., 2., ..., 3., 2., 3.],
       [3., 3., 2., ..., 3., 2., 3.],
       [2., 2., 2., ..., 2., 1., 2.],
       ...,
       [3., 3., 2., ..., 3., 2., 3.],
       [2., 2., 1., ..., 2., 2., 2.],
       [3., 3., 2., ..., 3., 2., 3.]])

In [109]:
d[30,1903]

1.0

In [121]:
Data_binary_numpy[[40,1903], :]

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [122]:
d[40,1903]

2.0

## Similaridad de Sokal

In [11]:
def Sokal_Similarity_1(i , r, Data):

    a, b, c, d, p = a_b_c_d_Matrix(Data)

    if a[i,r] + d[i,r] == 0 :

        Sokal_Similarity = 0

        
    else :

        Sokal_Similarity = (a[i,r] + d[i,r]) / p
        

    return Sokal_Similarity

In [22]:
Sokal_Similarity_1(i=1 , r=2, Data=Data_binary_numpy)

0.75

In [13]:
def Sokal_Similarity_2(i , r, a , d, p):


    if a[i,r] + d[i,r] == 0 :

        Sokal_Similarity = 0

        
    else :

        Sokal_Similarity = (a[i,r] + d[i,r]) / p
        

    return Sokal_Similarity

In [21]:
a, b, c, d, p = a_b_c_d_Matrix(Data_binary_numpy)

Sokal_Similarity_2(i=1, r=2, a=a, d=d, p=p)

0.75

In [43]:
def Matrix_Sim_Sokal_1(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                 M[i,r] = Sokal_Similarity_1(i, r, Data)
                      
    return M 

In [44]:
Matrix_Sim_Sokal_1(Data=Data_binary_numpy[0:300 , 0:300]) # 1.29 mins

array([[1.  , 1.  , 0.75, ..., 0.75, 0.75, 1.  ],
       [0.  , 1.  , 0.75, ..., 0.75, 0.75, 1.  ],
       [0.  , 0.  , 1.  , ..., 0.5 , 0.5 , 0.75],
       ...,
       [0.  , 0.  , 0.  , ..., 1.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 1.  ]])

In [52]:
def Matrix_Sim_Sokal_2(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    a, b, c, d, p = a_b_c_d_Matrix(Data)

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1

            else :

                 M[i,r] = Sokal_Similarity_2(i=i, r=r, a=a, d=d, p=p)
                      
    return M 

In [53]:
Matrix_Sim_Sokal_2(Data=Data_binary_numpy[0:500 , 0:500]) # 0.2 seg

array([[1.  , 1.  , 0.75, ..., 1.  , 1.  , 0.75],
       [0.  , 1.  , 0.75, ..., 1.  , 1.  , 0.75],
       [0.  , 0.  , 1.  , ..., 0.75, 0.75, 0.5 ],
       ...,
       [0.  , 0.  , 0.  , ..., 1.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 1.  ]])

In [64]:
M_Sim_Sokal = Matrix_Sim_Sokal_2(Data=Data_binary_numpy) # 3.4 seg

M_Sim_Sokal

array([[1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [0.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [0.  , 0.  , 1.  , ..., 0.75, 0.5 , 0.75],
       ...,
       [0.  , 0.  , 0.  , ..., 1.  , 0.75, 1.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 1.  ]])

In [65]:
M_Sim_Sokal = M_Sim_Sokal + M_Sim_Sokal.T - np.diag(np.repeat(1 , len(M_Sim_Sokal)), k=0)

M_Sim_Sokal

array([[1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [0.75, 0.75, 1.  , ..., 0.75, 0.5 , 0.75],
       ...,
       [1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [0.75, 0.75, 0.5 , ..., 0.75, 1.  , 0.75],
       [1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ]])

In [27]:
def Dist_Sokal(i, r, a, d, p):

    dist_Sokal = np.sqrt( Sokal_Similarity_2(i , i, a , d, p) + Sokal_Similarity_2(r , r, a , d, p) - 2*Sokal_Similarity_2(i , r, a , d, p) )

    return dist_Sokal  

In [28]:
a, b, c, d, p = a_b_c_d_Matrix(Data_binary_numpy)

Dist_Sokal(i=2, r=5, a=a, d=d, p=p)

1.0

In [32]:
def Matrix_Dist_Sokal(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    a, b, c, d, p = a_b_c_d_Matrix(Data)

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Sokal(i=i, r=r, a=a, d=d, p=p)
                      
    return M 

In [33]:
M_Dist_Sokal = Matrix_Dist_Sokal(Data=Data_binary_numpy)

M_Dist_Sokal

array([[0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.70710678, 1.        ,
        0.70710678],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.70710678],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [34]:
M_Dist_Sokal = M_Dist_Sokal + M_Dist_Sokal.T

M_Dist_Sokal

array([[0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.70710678, 0.70710678, 0.        , ..., 0.70710678, 1.        ,
        0.70710678],
       ...,
       [0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.70710678, 0.70710678, 1.        , ..., 0.70710678, 0.        ,
        0.70710678],
       [0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ]])

In [93]:
def Jaccard_Similarity_1(i, r, Data):

    a, b, c, d, p = a_b_c_d_Matrix(Data)

    if a[i,r] == 0 :

        Jaccard_Similarity = 0

    else :

        Jaccard_Similarity = a[i,r] / (a[i,r] + b[i,r] + c[i,r])


    return Jaccard_Similarity

In [94]:
Jaccard_Similarity_1(i=2, r=5, Data=Data_binary_numpy)

0

In [95]:
def Jaccard_Similarity_2(i , r, a , b, c):


    if a[i,r] == 0 :

        Jaccard_Similarity = 0

        
    else :

        Jaccard_Similarity = a[i,r] / (a[i,r] + b[i,r] + c[i,r])
        

    return Jaccard_Similarity

In [96]:
a, b, c, d, p = a_b_c_d_Matrix(Data=Data_binary_numpy)

Jaccard_Similarity_2(i=2, r=5, a=a , b=b, c=c)

0

In [97]:
def Matrix_Sim_Jaccard_1(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                 M[i,r] = Jaccard_Similarity_1(i, r, Data)
                      
    return M 

In [98]:
Matrix_Sim_Jaccard_1(Data=Data_binary_numpy[0:300,0:300])  # 1.52 min

array([[1. , 1. , 0.5, ..., 0. , 0. , 1. ],
       [0. , 1. , 0.5, ..., 0. , 0. , 1. ],
       [0. , 0. , 1. , ..., 0. , 0. , 0.5],
       ...,
       [0. , 0. , 0. , ..., 1. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 1. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 1. ]])

In [99]:
def Matrix_Sim_Jaccard_2(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    a, b, c, d, p = a_b_c_d_Matrix(Data=Data_binary_numpy)

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                 M[i,r] = Jaccard_Similarity_2(i , r , a , b , c)
                      
    return M 

In [100]:
Matrix_Sim_Jaccard_2(Data=Data_binary_numpy[0:300,0:300])

array([[1. , 1. , 0.5, ..., 0. , 0. , 1. ],
       [0. , 1. , 0.5, ..., 0. , 0. , 1. ],
       [0. , 0. , 1. , ..., 0. , 0. , 0.5],
       ...,
       [0. , 0. , 0. , ..., 1. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 1. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 1. ]])

In [101]:
M_Jaccard = Matrix_Sim_Jaccard_2(Data=Data_binary_numpy)

M_Jaccard 

array([[1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [0.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.5       , 0.33333333,
        0.5       ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.5       ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [102]:
M_Jaccard = M_Jaccard + M_Jaccard.T - np.diag(np.repeat(1 , len(M_Jaccard)), k=0)

M_Jaccard 

array([[1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [0.5       , 0.5       , 1.        , ..., 0.5       , 0.33333333,
        0.5       ],
       ...,
       [1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [0.5       , 0.5       , 0.33333333, ..., 0.5       , 1.        ,
        0.5       ],
       [1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ]])

In [106]:
def Dist_Jaccard(i , r, a , b, c):

    Dist_Jaccard = np.sqrt( Jaccard_Similarity_2(i , i, a , b, c) + Jaccard_Similarity_2(r , r, a , b, c) - 2*Jaccard_Similarity_2(i , r, a , b, c) )

    return Dist_Jaccard  

In [111]:
a, b, c, d, p = a_b_c_d_Matrix(Data_binary_numpy)

Dist_Jaccard(i=2 , r=5, a=a , b=b, c=c)

0.0

In [109]:
def Matrix_Dist_Jaccard(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    a, b, c, d, p = a_b_c_d_Matrix(Data)

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Jaccard(i=i, r=r, a=a, b=b, c=c)
                      
    return M 

In [110]:
M_Dist_Jaccard = Matrix_Dist_Jaccard(Data=Data_binary_numpy)

M_Dist_Jaccard

array([[0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.15470054,
        1.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [112]:
M_Dist_Jaccard = M_Dist_Jaccard + M_Dist_Jaccard.T 

M_Dist_Jaccard

array([[0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 1.        , 1.15470054,
        1.        ],
       ...,
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 1.15470054, ..., 1.        , 0.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ]])

In [76]:
from joblib import Parallel, delayed

import multiprocessing

In [85]:
def alpha(x_i, x_r, Data):

    # Es necesario que Data sea un numpy array

    X = Data

    alpha = np.repeat(0, X.shape[1])

    ifelse  =  lambda k :  1  if x_i[k] == x_r[k]   else  0   # Es más eficiente que un bucle condicional.

    for k in range(0, X.shape[1]-1) :

        alpha[k] = ifelse(k)

    alpha = alpha.sum()

    return(alpha)   

In [33]:
Data_multiclass_numpy[2,:] 

array([2., 4., 1.])

In [34]:
Data_multiclass_numpy[5,:] 

array([2., 1., 2.])

In [86]:
alpha(x_i=Data_multiclass_numpy[2,:] , x_r=Data_multiclass_numpy[5,:], Data=Data_multiclass_numpy)

1

In [31]:
Data_multiclass_numpy[15,:] 

array([2., 4., 0.])

In [29]:
Data_multiclass_numpy[14,:]

array([2., 4., 2.])

In [87]:
alpha(x_i=Data_multiclass_numpy[14,:] , x_r=Data_multiclass_numpy[15,:], Data=Data_multiclass_numpy)

2

In [88]:
def matches_similarity(x_i, x_r, Data):

    # Es necesario que Data sea un numpy array

    X = Data

    p = X.shape[1]

    matches_similarity = alpha(x_i, x_r, X) / p

    return(matches_similarity)

In [89]:
matches_similarity(x_i=Data_multiclass_numpy[2,:] , x_r=Data_multiclass_numpy[5,:], Data=Data_multiclass_numpy)

0.3333333333333333

In [90]:
matches_similarity(x_i=Data_multiclass_numpy[14,:] , x_r=Data_multiclass_numpy[15,:], Data=Data_multiclass_numpy)

0.6666666666666666

In [91]:
def Matrix_Sim_Matches(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                 M[i,r] = matches_similarity(x_i=Data[i,:], x_r=Data[r,:], Data=Data)
                      
    return M 

In [92]:
M_matches = Matrix_Sim_Matches(Data=Data_multiclass_numpy)

M_matches 

array([[1.        , 0.33333333, 0.33333333, ..., 0.33333333, 0.33333333,
        0.        ],
       [0.        , 1.        , 0.66666667, ..., 0.33333333, 0.33333333,
        0.33333333],
       [0.        , 0.        , 1.        , ..., 0.33333333, 0.33333333,
        0.33333333],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.33333333,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [93]:
M_matches = M_matches + M_matches.T

M_matches

array([[2.        , 0.33333333, 0.33333333, ..., 0.33333333, 0.33333333,
        0.        ],
       [0.33333333, 2.        , 0.66666667, ..., 0.33333333, 0.33333333,
        0.33333333],
       [0.33333333, 0.66666667, 2.        , ..., 0.33333333, 0.33333333,
        0.33333333],
       ...,
       [0.33333333, 0.33333333, 0.33333333, ..., 2.        , 0.33333333,
        0.        ],
       [0.33333333, 0.33333333, 0.33333333, ..., 0.33333333, 2.        ,
        0.        ],
       [0.        , 0.33333333, 0.33333333, ..., 0.        , 0.        ,
        2.        ]])

In [94]:
def Dist_Matches(x_i, x_r, Data):

    Dist_Matches = np.sqrt(matches_similarity(x_i, x_i, Data) +  matches_similarity(x_r, x_r, Data) - 2*matches_similarity(x_i, x_r, Data) )

    return( Dist_Matches )

In [95]:
matches_similarity(x_i=Data_multiclass_numpy[2,:] , x_r=Data_multiclass_numpy[5,:], Data=Data_multiclass_numpy)

0.3333333333333333

In [96]:
def Matrix_Dist_Matches(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))
   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Matches(x_i=Data[i,:] , x_r=Data[r,:], Data=Data)
                      
    return M 

In [97]:
M_Dist_Matches = Matrix_Dist_Matches(Data=Data_multiclass_numpy)

M_Dist_Matches

In [ ]:
M_Dist_Matches = M_Dist_Matches + M_Dist_Matches.T

M_Dist_Matches