In [160]:
import pandas as pd
import numpy as np

In [161]:
Data = pd.read_csv('House_Price_Regression.csv')

Data['type'] = np.random.uniform(low=0, high=3, size=len(Data)).round()

Data['rating'] = np.random.uniform(low=0, high=5, size=len(Data)).round()

Data.head()

neighborhood_recode   latitude  longitude    price  no_of_bedrooms  \
0                 46.0  25.113208  55.138932  2700000               1   
1                 46.0  25.106809  55.151201  2850000               2   
2                 36.0  25.063302  55.137728  1150000               3   
3                 11.0  25.227295  55.341761  2850000               2   
4                 46.0  25.114275  55.139764  1729200               0   

   no_of_bathrooms  quality_recode  maid_room_recode  unfurnished_recode  \
0                2             2.0               0.0                 0.0   
1                2             2.0               0.0                 0.0   
2                5             2.0               1.0                 1.0   
3                3             1.0               0.0                 1.0   
4                1             2.0               0.0                 0.0   

   balcony_recode  ...  private_jacuzzi_recode  private_pool_recode  \
0             1.0  ...                     0.0                  0.0   
1             1.0  ...                     0.0                  0.0   
2             1.0  ...                     1.0                  0.0   
3             1.0  ...                     0.0                  0.0   
4             0.0  ...                     0.0                  0.0   

   security_recode  shared_gym_recode  shared_pool_recode  shared_spa_recode  \
0              0.0                1.0                 0.0                0.0   
1              0.0                1.0                 1.0                0.0   
2              1.0                1.0                 1.0                0.0   
3              0.0                0.0                 0.0                0.0   
4              1.0                1.0                 1.0                1.0   

   view_of_water_recode  size_in_m_2  type  rating  
0                   1.0   100.242337   1.0     2.0  
1                   1.0   146.972546   1.0     1.0  
2                   1.0   181.253753   3.0     1.0  
3                   0.0   187.664060   1.0     0.0  
4                   1.0    47.101821   1.0     1.0  

[5 rows x 31 columns]

In [162]:
Data_quant = Data.loc[: , ['latitude', 'longitude', 'price', 'size_in_m_2', 'no_of_bedrooms', 'no_of_bathrooms']]

In [163]:
Data_quant.head()

latitude  longitude    price  size_in_m_2  no_of_bedrooms  no_of_bathrooms
0  25.113208  55.138932  2700000   100.242337               1                2
1  25.106809  55.151201  2850000   146.972546               2                2
2  25.063302  55.137728  1150000   181.253753               3                5
3  25.227295  55.341761  2850000   187.664060               2                3
4  25.114275  55.139764  1729200    47.101821               0                1

In [164]:
Data_binary = Data.loc[: , ['private_garden_recode', 'private_gym_recode', 'private_jacuzzi_recode', 'balcony_recode']]

Data_binary.head()

private_garden_recode  private_gym_recode  private_jacuzzi_recode  \
0                    0.0                 0.0                     0.0   
1                    0.0                 0.0                     0.0   
2                    0.0                 0.0                     1.0   
3                    0.0                 0.0                     0.0   
4                    0.0                 0.0                     0.0   

   balcony_recode  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             0.0

In [165]:
Data_multiclass = Data.loc[: , ['quality_recode', 'rating', 'type']]

Data_multiclass.head()

quality_recode  rating  type
0             2.0     2.0   1.0
1             2.0     1.0   1.0
2             2.0     1.0   3.0
3             1.0     0.0   1.0
4             2.0     1.0   1.0

In [166]:
Data_mixed = Data.loc[: , ['latitude', 'longitude', 'price', 'size_in_m_2', 'no_of_bedrooms', 'no_of_bathrooms','private_garden_recode', 'private_gym_recode', 'private_jacuzzi_recode', 'balcony_recode','quality_recode', 'rating', 'type']]

Data_mixed.head()

latitude  longitude    price  size_in_m_2  no_of_bedrooms  \
0  25.113208  55.138932  2700000   100.242337               1   
1  25.106809  55.151201  2850000   146.972546               2   
2  25.063302  55.137728  1150000   181.253753               3   
3  25.227295  55.341761  2850000   187.664060               2   
4  25.114275  55.139764  1729200    47.101821               0   

   no_of_bathrooms  private_garden_recode  private_gym_recode  \
0                2                    0.0                 0.0   
1                2                    0.0                 0.0   
2                5                    0.0                 0.0   
3                3                    0.0                 0.0   
4                1                    0.0                 0.0   

   private_jacuzzi_recode  balcony_recode  quality_recode  rating  type  
0                     0.0             1.0             2.0     2.0   1.0  
1                     0.0             1.0             2.0     1.0   1.0  
2                     1.0             1.0             2.0     1.0   3.0  
3                     0.0             1.0             1.0     0.0   1.0  
4                     0.0             0.0             2.0     1.0   1.0

In [167]:
Data_quant_numpy = Data_quant.to_numpy()
Data_binary_numpy = Data_binary.to_numpy()
Data_multiclass_numpy = Data_multiclass.to_numpy()
Data_mixed_numpy = Data_mixed.to_numpy()

## Distancia Euclidea

In [168]:
def Dist_Euclidea(x_i, x_r):

        Dist_Euclidea = ( ( x_i - x_r )**2 ).sum()

        Dist_Euclidea = np.sqrt(Dist_Euclidea)

        return Dist_Euclidea

In [169]:
Dist_Euclidea(Data_quant.iloc[2,:] , Data_quant.iloc[5,:])

1969900.0019225744

In [170]:
def Matrix_Dist_Euclidea(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Euclidea(Data[i,:] , Data[r,:])   

                      
    return M 

In [171]:
M_Euclidean = Matrix_Dist_Euclidea(Data=Data_quant_numpy)

In [172]:
M_Euclidean

array([[      0.        ,  150000.00728238, 1550000.00212124, ...,
         200000.01565902, 2025000.00024491, 1939113.00017324],
       [      0.        ,       0.        , 1700000.00034859, ...,
          50000.01055292, 2175000.00140691, 2089113.00126347],
       [      0.        ,       0.        ,       0.        , ...,
        1750000.00000111,  475000.01333737,  389113.0147095 ],
       ...,
       [      0.        ,       0.        ,       0.        , ...,
              0.        , 2225000.00274952, 2139113.00257909],
       [      0.        ,       0.        ,       0.        , ...,
              0.        ,       0.        ,   85887.00018092],
       [      0.        ,       0.        ,       0.        , ...,
              0.        ,       0.        ,       0.        ]])

In [173]:
M_Euclidean = M_Euclidean + M_Euclidean.T

M_Euclidean

array([[      0.        ,  150000.00728238, 1550000.00212124, ...,
         200000.01565902, 2025000.00024491, 1939113.00017324],
       [ 150000.00728238,       0.        , 1700000.00034859, ...,
          50000.01055292, 2175000.00140691, 2089113.00126347],
       [1550000.00212124, 1700000.00034859,       0.        , ...,
        1750000.00000111,  475000.01333737,  389113.0147095 ],
       ...,
       [ 200000.01565902,   50000.01055292, 1750000.00000111, ...,
              0.        , 2225000.00274952, 2139113.00257909],
       [2025000.00024491, 2175000.00140691,  475000.01333737, ...,
        2225000.00274952,       0.        ,   85887.00018092],
       [1939113.00017324, 2089113.00126347,  389113.0147095 , ...,
        2139113.00257909,   85887.00018092,       0.        ]])

## Distancia de Minkowski

In [174]:
def Dist_Minkowski(x_i, x_r, q):

    Dist_Minkowski = ( ( ( abs( x_i - x_r) )**q ).sum() )**(1/q)

    return Dist_Minkowski

In [175]:
Dist_Minkowski(Data_quant.iloc[2,:], Data_quant.iloc[5,:], q=1)

1969992.0102169998

In [176]:
Dist_Minkowski(Data_quant.iloc[2,:], Data_quant.iloc[5,:], q=2)

1969900.0019225744

In [177]:
Dist_Minkowski(Data_quant.iloc[2,:], Data_quant.iloc[5,:], q=3)

1969900.000000055

In [178]:
Dist_Minkowski(Data_quant.iloc[2,:], Data_quant.iloc[5,:], q=10)

1969900.0000000016

In [179]:
def Matrix_Dist_Minkowski(Data, q):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Minkowski(Data[i,:] , Data[r,:], q)   

                      
    return M 

In [180]:
M_Minkowski = Matrix_Dist_Minkowski(Data=Data_quant_numpy , q=1)

M_Minkowski

array([[      0.      ,  150047.748877, 1550086.062526, ...,
         200084.359869, 2025031.624379, 1939138.969796],
       [      0.      ,       0.      , 1700038.338187, ...,
          50036.62379 , 2175079.33592 , 2089186.681337],
       [      0.      ,       0.      ,       0.      , ...,
        1750002.301489,  475117.608205,  389224.964166],
       ...,
       [      0.      ,       0.      ,       0.      , ...,
              0.      , 2225115.802424, 2139223.298103],
       [      0.      ,       0.      ,       0.      , ...,
              0.      ,       0.      ,   85892.654583],
       [      0.      ,       0.      ,       0.      , ...,
              0.      ,       0.      ,       0.      ]])

In [181]:
M_Minkowski = M_Minkowski + M_Minkowski.T

M_Minkowski

array([[      0.      ,  150047.748877, 1550086.062526, ...,
         200084.359869, 2025031.624379, 1939138.969796],
       [ 150047.748877,       0.      , 1700038.338187, ...,
          50036.62379 , 2175079.33592 , 2089186.681337],
       [1550086.062526, 1700038.338187,       0.      , ...,
        1750002.301489,  475117.608205,  389224.964166],
       ...,
       [ 200084.359869,   50036.62379 , 1750002.301489, ...,
              0.      , 2225115.802424, 2139223.298103],
       [2025031.624379, 2175079.33592 ,  475117.608205, ...,
        2225115.802424,       0.      ,   85892.654583],
       [1939138.969796, 2089186.681337,  389224.964166, ...,
        2139223.298103,   85892.654583,       0.      ]])

## Distancia Canberra

In [182]:
def Dist_Canberra(x_i, x_r):

    numerator =  abs( x_i - x_r )

    denominator =  ( abs(x_i) + abs(x_r) )
       
    numerator=np.array([numerator], dtype=float)

    denominator=np.array([denominator], dtype=float)

    # The following code is to eliminate zero division problems

    Dist_Canberra = ( np.divide( numerator , denominator , out=np.zeros_like(numerator), where=denominator!=0) ).sum() 

    return Dist_Canberra

In [183]:
Dist_Canberra(Data.iloc[2,:] , Data.iloc[5,:])

9.3284791957755

In [184]:
def Matrix_Dist_Canberra(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Canberra(Data[i,:] , Data[r,:])   

                      
    return M 

In [185]:
M_Canberra = Matrix_Dist_Canberra(Data=Data_quant_numpy)

M_Canberra

array([[0.        , 0.5496257 , 1.61996314, ..., 1.25082356, 0.78797391,
        0.70959891],
       [0.        , 0.        , 1.15900459, ..., 0.74009173, 1.31434216,
        1.24077176],
       [0.        , 0.        , 0.        , ..., 0.44223489, 1.63990915,
        1.55106392],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.00032192,
        1.93106183],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.09956138],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [186]:
M_Canberra = M_Canberra + M_Canberra.T

M_Canberra

array([[0.        , 0.5496257 , 1.61996314, ..., 1.25082356, 0.78797391,
        0.70959891],
       [0.5496257 , 0.        , 1.15900459, ..., 0.74009173, 1.31434216,
        1.24077176],
       [1.61996314, 1.15900459, 0.        , ..., 0.44223489, 1.63990915,
        1.55106392],
       ...,
       [1.25082356, 0.74009173, 0.44223489, ..., 0.        , 2.00032192,
        1.93106183],
       [0.78797391, 1.31434216, 1.63990915, ..., 2.00032192, 0.        ,
        0.09956138],
       [0.70959891, 1.24077176, 1.55106392, ..., 1.93106183, 0.09956138,
        0.        ]])

## Distancia Pearson

In [187]:
def Dist_Pearson(x_i, x_r, Data) :

    # Si Data  es un pd.DataFrame --> hay que convertilos antes a numpy con Data.to_numpy()

    Dist_Pearson = ( ( x_i - x_r )**2 / np.var(Data , axis=0, ddof=1) ).sum()

    # np.var(Data , axis=0, ddof=1)  calcula la cuasi-varianza (ddof=1) por columnas (axis=0)

    Dist_Pearson = np.sqrt(Dist_Pearson)

    return Dist_Pearson

In [188]:
Dist_Pearson(x_i=Data_quant_numpy[2,:], x_r=Data_quant_numpy[5,:], Data=Data_quant_numpy)

3.8239347754243425

In [189]:
def Matrix_Dist_Pearson(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Pearson(Data[i,:] , Data[r,:], Data=Data)   

                      
    return M 

In [190]:
M_Pearson = Matrix_Dist_Pearson(Data=Data_quant_numpy)

M_Pearson

array([[0.        , 1.21345279, 3.77819153, ..., 4.95085256, 1.66393723,
        0.94314867],
       [0.        , 0.        , 3.17880538, ..., 4.43821303, 2.03523139,
        1.60958264],
       [0.        , 0.        , 0.        , ..., 3.82999056, 4.01162596,
        3.76955491],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 4.69603617,
        5.13174853],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.09780835],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [191]:
M_Pearson = M_Pearson + M_Pearson.T

M_Pearson

array([[0.        , 1.21345279, 3.77819153, ..., 4.95085256, 1.66393723,
        0.94314867],
       [1.21345279, 0.        , 3.17880538, ..., 4.43821303, 2.03523139,
        1.60958264],
       [3.77819153, 3.17880538, 0.        , ..., 3.82999056, 4.01162596,
        3.76955491],
       ...,
       [4.95085256, 4.43821303, 3.82999056, ..., 0.        , 4.69603617,
        5.13174853],
       [1.66393723, 2.03523139, 4.01162596, ..., 4.69603617, 0.        ,
        1.09780835],
       [0.94314867, 1.60958264, 3.76955491, ..., 5.13174853, 1.09780835,
        0.        ]])

## Distancia de Mahalanobis

In [192]:
def Dist_Mahalanobis_1(x_i, x_r, Data):

    # All the columns of Data must be type = 'float' or 'int' (specially not 'object'), in other case we will find 
    # dimensional problems when Python compute   x @ S_inv @ x.T

    x = (x_i - x_r)

    x = np.array([x]) # necessary step to transpose a 1D array

    S_inv = np.linalg.inv( np.cov(Data , rowvar=False) ) # inverse of covariance matrix

    Dist_Maha = np.sqrt( x @ S_inv @ x.T )  # x @ S_inv @ x.T = np.matmul( np.matmul(x , S_inv) , x.T )

    Dist_Maha = float(Dist_Maha)

    return Dist_Maha

In [193]:
Dist_Mahalanobis_1(Data_quant_numpy[2,:] , Data_quant_numpy[5,:] , Data=Data_quant_numpy )

3.931396144771864

In [194]:
def Dist_Mahalanobis_2(x_i, x_r, S_inv):  # Más eficiente que la anterior

    # All the columns of Data must be type = 'float' or 'int' (specially not 'object'), in other case we will find 
    # dimensional problems when Python compute   x @ S_inv @ x.T

    x = (x_i - x_r)

    x = np.array([x]) # necessary step to transpose a 1D array

    Dist_Maha = np.sqrt( x @ S_inv @ x.T )  # x @ S_inv @ x.T = np.matmul( np.matmul(x , S_inv) , x.T )

    Dist_Maha = float(Dist_Maha)

    return Dist_Maha

In [195]:
Dist_Mahalanobis_2(x_i = Data_quant_numpy[2,:] , x_r = Data_quant_numpy[5,:] , S_inv = np.linalg.inv( np.cov(Data_quant_numpy , rowvar=False) ) )

3.931396144771864

In [196]:
def Dist_Mahalanobis_3(x, S_inv):  # Más eficiente que la anterior

    # All the columns of Data must be type = 'float' or 'int' (specially not 'object'), in other case we will find 
    # dimensional problems when Python compute   x @ S_inv @ x.T

    # x = (x_i - x_r)

    # x = np.array([x]) # necessary step to transpose a 1D array

    Dist_Maha = np.sqrt( x @ S_inv @ x.T )  # x @ S_inv @ x.T = np.matmul( np.matmul(x , S_inv) , x.T )

    Dist_Maha = float(Dist_Maha)

    return Dist_Maha

In [197]:
Dist_Mahalanobis_3(x = np.array([Data_quant_numpy[2,:] - Data_quant_numpy[5,:]]) , S_inv=np.linalg.inv( np.cov(Data_quant_numpy , rowvar=False) ))

3.931396144771864

In [198]:
def Matrix_Dist_Mahalanobis_1(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Mahalanobis_1(x_i = Data[i,:] , x_r = Data[r,:] , Data=Data )

                      
    return M 

In [199]:
Matrix_Dist_Mahalanobis_1(Data=Data_quant_numpy[0:1000 , 0:1000]) # 2.25 mins

array([[0.        , 2.16321817, 3.81131086, ..., 2.74083537, 3.84799958,
        1.06041471],
       [0.        , 0.        , 4.29953104, ..., 2.76698155, 2.78100414,
        2.20791581],
       [0.        , 0.        , 0.        , ..., 2.63546884, 4.34269664,
        3.32469143],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.18534065,
        1.8408748 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.09496075],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [200]:
Matrix_Dist_Mahalanobis_1(Data=Data_quant_numpy) # 8.52 mins

array([[0.        , 2.11289055, 3.7975463 , ..., 4.51559865, 2.31688444,
        1.10588047],
       [0.        , 0.        , 4.35615967, ..., 4.93340427, 2.74011739,
        2.12938584],
       [0.        , 0.        , 0.        , ..., 3.17779509, 3.49432487,
        3.23723317],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 3.58695453,
        4.11275247],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.46894947],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [201]:
def Matrix_Dist_Mahalanobis_2(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    S_inv = np.linalg.inv( np.cov(Data , rowvar=False) )

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Mahalanobis_2(x_i = Data[i,:] , x_r = Data[r,:] , S_inv = S_inv  )

                      
    return M 

In [202]:
Matrix_Dist_Mahalanobis_2(Data=Data_quant_numpy[0:1000 , 0:1000]) # 6.8 seg

array([[0.        , 2.16321817, 3.81131086, ..., 2.74083537, 3.84799958,
        1.06041471],
       [0.        , 0.        , 4.29953104, ..., 2.76698155, 2.78100414,
        2.20791581],
       [0.        , 0.        , 0.        , ..., 2.63546884, 4.34269664,
        3.32469143],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.18534065,
        1.8408748 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.09496075],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [203]:
Matrix_Dist_Mahalanobis_2(Data=Data_quant_numpy) # 22.5 seg

array([[0.        , 2.11289055, 3.7975463 , ..., 4.51559865, 2.31688444,
        1.10588047],
       [0.        , 0.        , 4.35615967, ..., 4.93340427, 2.74011739,
        2.12938584],
       [0.        , 0.        , 0.        , ..., 3.17779509, 3.49432487,
        3.23723317],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 3.58695453,
        4.11275247],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.46894947],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [204]:
def Matrix_Dist_Mahalanobis_3(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    S_inv=np.linalg.inv( np.cov(Data , rowvar=False) )

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Mahalanobis_3(x = np.array([Data[i,:] - Data[r,:]]) , S_inv=S_inv ) 

                      
    return M 

In [205]:
Matrix_Dist_Mahalanobis_3(Data=Data_quant_numpy[0:1000 , 0:1000]) # 4.8 seg

array([[0.        , 2.16321817, 3.81131086, ..., 2.74083537, 3.84799958,
        1.06041471],
       [0.        , 0.        , 4.29953104, ..., 2.76698155, 2.78100414,
        2.20791581],
       [0.        , 0.        , 0.        , ..., 2.63546884, 4.34269664,
        3.32469143],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 2.18534065,
        1.8408748 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.09496075],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [206]:
M_Mahalanobis = Matrix_Dist_Mahalanobis_3(Data=Data_quant_numpy) # 19.7 seg

M_Mahalanobis

array([[0.        , 2.11289055, 3.7975463 , ..., 4.51559865, 2.31688444,
        1.10588047],
       [0.        , 0.        , 4.35615967, ..., 4.93340427, 2.74011739,
        2.12938584],
       [0.        , 0.        , 0.        , ..., 3.17779509, 3.49432487,
        3.23723317],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 3.58695453,
        4.11275247],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.46894947],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [207]:
M_Mahalanobis = M_Mahalanobis + M_Mahalanobis.T

M_Mahalanobis

array([[0.        , 2.11289055, 3.7975463 , ..., 4.51559865, 2.31688444,
        1.10588047],
       [2.11289055, 0.        , 4.35615967, ..., 4.93340427, 2.74011739,
        2.12938584],
       [3.7975463 , 4.35615967, 0.        , ..., 3.17779509, 3.49432487,
        3.23723317],
       ...,
       [4.51559865, 4.93340427, 3.17779509, ..., 0.        , 3.58695453,
        4.11275247],
       [2.31688444, 2.74011739, 3.49432487, ..., 3.58695453, 0.        ,
        1.46894947],
       [1.10588047, 2.12938584, 3.23723317, ..., 4.11275247, 1.46894947,
        0.        ]])

In [208]:
def a_b_c_d_Matrix(Data):

    X = Data

    a = X @ X.T

    n = X.shape[0]

    p = X.shape[1]

    ones_matrix = np.ones((n, p)) 

    b = (ones_matrix - X) @ X.T

    c = b.T

    d = (ones_matrix - X) @ (ones_matrix - X).T

    return a , b , c , d , p

In [209]:
a, b, c, d, p = a_b_c_d_Matrix(Data_binary_numpy)

In [210]:
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 2., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 2., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [211]:
Data_binary_numpy[[30,1903], :]

array([[0., 1., 0., 1.],
       [1., 0., 0., 1.]])

In [212]:
a[30 , 1903]

1.0

In [213]:
Data_binary_numpy[[40,1903], :]

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [214]:
a[40 , 1903]

1.0

In [215]:
b

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.]])

In [216]:
Data_binary_numpy[[30,1903], :]

array([[0., 1., 0., 1.],
       [1., 0., 0., 1.]])

In [217]:
b[30 , 1903]

1.0

In [218]:
Data_binary_numpy[[40,1903], :]

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [219]:
b[40,1903]

1.0

In [220]:
c

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [221]:
c[30, 1903]

1.0

In [222]:
Data_binary_numpy[[40,1903], :]

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [223]:
c[40, 1903]

0.0

In [224]:
d

array([[3., 3., 2., ..., 3., 2., 3.],
       [3., 3., 2., ..., 3., 2., 3.],
       [2., 2., 2., ..., 2., 1., 2.],
       ...,
       [3., 3., 2., ..., 3., 2., 3.],
       [2., 2., 1., ..., 2., 2., 2.],
       [3., 3., 2., ..., 3., 2., 3.]])

In [225]:
d[30,1903]

1.0

In [226]:
Data_binary_numpy[[40,1903], :]

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [227]:
d[40,1903]

2.0

## Similaridad de Sokal

In [228]:
def Sokal_Similarity_1(i , r, Data):

    a, b, c, d, p = a_b_c_d_Matrix(Data)

    if a[i,r] + d[i,r] == 0 :

        Sokal_Similarity = 0

        
    else :

        Sokal_Similarity = (a[i,r] + d[i,r]) / p
        

    return Sokal_Similarity

In [229]:
Sokal_Similarity_1(i=1 , r=2, Data=Data_binary_numpy)

0.75

In [230]:
def Sokal_Similarity_2(i , r, a , d, p):


    if a[i,r] + d[i,r] == 0 :

        Sokal_Similarity = 0

        
    else :

        Sokal_Similarity = (a[i,r] + d[i,r]) / p
        

    return Sokal_Similarity

In [231]:
a, b, c, d, p = a_b_c_d_Matrix(Data_binary_numpy)

Sokal_Similarity_2(i=1, r=2, a=a, d=d, p=p)

0.75

In [232]:
def Matrix_Sim_Sokal_1(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                 M[i,r] = Sokal_Similarity_1(i, r, Data)
                      
    return M 

In [233]:
Matrix_Sim_Sokal_1(Data=Data_binary_numpy[0:300 , 0:300]) # 1.29 mins

array([[1.  , 1.  , 0.75, ..., 0.75, 0.75, 1.  ],
       [0.  , 1.  , 0.75, ..., 0.75, 0.75, 1.  ],
       [0.  , 0.  , 1.  , ..., 0.5 , 0.5 , 0.75],
       ...,
       [0.  , 0.  , 0.  , ..., 1.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 1.  ]])

In [234]:
def Matrix_Sim_Sokal_2(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    a, b, c, d, p = a_b_c_d_Matrix(Data)

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1

            else :

                 M[i,r] = Sokal_Similarity_2(i=i, r=r, a=a, d=d, p=p)
                      
    return M 

In [235]:
Matrix_Sim_Sokal_2(Data=Data_binary_numpy[0:500 , 0:500]) # 0.2 seg

array([[1.  , 1.  , 0.75, ..., 1.  , 1.  , 0.75],
       [0.  , 1.  , 0.75, ..., 1.  , 1.  , 0.75],
       [0.  , 0.  , 1.  , ..., 0.75, 0.75, 0.5 ],
       ...,
       [0.  , 0.  , 0.  , ..., 1.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 1.  ]])

In [236]:
M_Sim_Sokal = Matrix_Sim_Sokal_2(Data=Data_binary_numpy) # 3.4 seg

M_Sim_Sokal

array([[1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [0.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [0.  , 0.  , 1.  , ..., 0.75, 0.5 , 0.75],
       ...,
       [0.  , 0.  , 0.  , ..., 1.  , 0.75, 1.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.75],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 1.  ]])

In [237]:
M_Sim_Sokal = M_Sim_Sokal + M_Sim_Sokal.T - np.diag(np.repeat(1 , len(M_Sim_Sokal)), k=0)

M_Sim_Sokal

array([[1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [0.75, 0.75, 1.  , ..., 0.75, 0.5 , 0.75],
       ...,
       [1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ],
       [0.75, 0.75, 0.5 , ..., 0.75, 1.  , 0.75],
       [1.  , 1.  , 0.75, ..., 1.  , 0.75, 1.  ]])

In [238]:
def Dist_Sokal(i, r, a, d, p):

    dist_Sokal = np.sqrt( Sokal_Similarity_2(i , i, a , d, p) + Sokal_Similarity_2(r , r, a , d, p) - 2*Sokal_Similarity_2(i , r, a , d, p) )

    return dist_Sokal  

In [295]:
a, b, c, d, p = a_b_c_d_Matrix(Data_binary_numpy)

Dist_Sokal(i=1, r=2, a=a, d=d, p=p)

0.7071067811865476

In [240]:
def Matrix_Dist_Sokal(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    a, b, c, d, p = a_b_c_d_Matrix(Data)

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Sokal(i=i, r=r, a=a, d=d, p=p)
                      
    return M 

In [241]:
M_Dist_Sokal = Matrix_Dist_Sokal(Data=Data_binary_numpy)

M_Dist_Sokal

array([[0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.70710678, 1.        ,
        0.70710678],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.70710678],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [242]:
M_Dist_Sokal = M_Dist_Sokal + M_Dist_Sokal.T

M_Dist_Sokal

array([[0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.70710678, 0.70710678, 0.        , ..., 0.70710678, 1.        ,
        0.70710678],
       ...,
       [0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ],
       [0.70710678, 0.70710678, 1.        , ..., 0.70710678, 0.        ,
        0.70710678],
       [0.        , 0.        , 0.70710678, ..., 0.        , 0.70710678,
        0.        ]])

## Similaridad de Jaccard

In [243]:
def Jaccard_Similarity_1(i, r, Data):

    a, b, c, d, p = a_b_c_d_Matrix(Data)

    if a[i,r] == 0 :

        Jaccard_Similarity = 0

    else :

        Jaccard_Similarity = a[i,r] / (a[i,r] + b[i,r] + c[i,r])


    return Jaccard_Similarity

In [244]:
Jaccard_Similarity_1(i=2, r=5, Data=Data_binary_numpy)

0

In [245]:
def Jaccard_Similarity_2(i , r, a , b, c):


    if a[i,r] == 0 :

        Jaccard_Similarity = 0

        
    else :

        Jaccard_Similarity = a[i,r] / (a[i,r] + b[i,r] + c[i,r])
        

    return Jaccard_Similarity

In [246]:
a, b, c, d, p = a_b_c_d_Matrix(Data=Data_binary_numpy)

Jaccard_Similarity_2(i=2, r=5, a=a , b=b, c=c)

0

In [247]:
def Matrix_Sim_Jaccard_1(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                 M[i,r] = Jaccard_Similarity_1(i, r, Data)
                      
    return M 

In [248]:
Matrix_Sim_Jaccard_1(Data=Data_binary_numpy[0:300,0:300])  # 1.52 min

array([[1. , 1. , 0.5, ..., 0. , 0. , 1. ],
       [0. , 1. , 0.5, ..., 0. , 0. , 1. ],
       [0. , 0. , 1. , ..., 0. , 0. , 0.5],
       ...,
       [0. , 0. , 0. , ..., 1. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 1. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 1. ]])

In [249]:
def Matrix_Sim_Jaccard_2(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    a, b, c, d, p = a_b_c_d_Matrix(Data=Data_binary_numpy)

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                 M[i,r] = Jaccard_Similarity_2(i , r , a , b , c)
                      
    return M 

In [250]:
Matrix_Sim_Jaccard_2(Data=Data_binary_numpy[0:300,0:300])

array([[1. , 1. , 0.5, ..., 0. , 0. , 1. ],
       [0. , 1. , 0.5, ..., 0. , 0. , 1. ],
       [0. , 0. , 1. , ..., 0. , 0. , 0.5],
       ...,
       [0. , 0. , 0. , ..., 1. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 1. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 1. ]])

In [251]:
M_Jaccard = Matrix_Sim_Jaccard_2(Data=Data_binary_numpy)

M_Jaccard 

array([[1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [0.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.5       , 0.33333333,
        0.5       ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.5       ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [252]:
M_Jaccard = M_Jaccard + M_Jaccard.T - np.diag(np.repeat(1 , len(M_Jaccard)), k=0)

M_Jaccard 

array([[1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [0.5       , 0.5       , 1.        , ..., 0.5       , 0.33333333,
        0.5       ],
       ...,
       [1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ],
       [0.5       , 0.5       , 0.33333333, ..., 0.5       , 1.        ,
        0.5       ],
       [1.        , 1.        , 0.5       , ..., 1.        , 0.5       ,
        1.        ]])

In [253]:
def Dist_Jaccard(i , r, a , b, c):

    Dist_Jaccard = np.sqrt( Jaccard_Similarity_2(i , i, a , b, c) + Jaccard_Similarity_2(r , r, a , b, c) - 2*Jaccard_Similarity_2(i , r, a , b, c) )

    return Dist_Jaccard  

In [254]:
a, b, c, d, p = a_b_c_d_Matrix(Data_binary_numpy)

Dist_Jaccard(i=2 , r=5, a=a , b=b, c=c)

1.0

In [255]:
def Matrix_Dist_Jaccard(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

    a, b, c, d, p = a_b_c_d_Matrix(Data)

   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                 M[i,r] = 0

             else :

                 M[i,r] = Dist_Jaccard(i=i, r=r, a=a, b=b, c=c)
                      
    return M 

In [256]:
M_Dist_Jaccard = Matrix_Dist_Jaccard(Data=Data_binary_numpy)

M_Dist_Jaccard

array([[0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.15470054,
        1.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [257]:
M_Dist_Jaccard = M_Dist_Jaccard + M_Dist_Jaccard.T 

M_Dist_Jaccard

array([[0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 1.        , 1.15470054,
        1.        ],
       ...,
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 1.15470054, ..., 1.        , 0.        ,
        1.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ]])

## Similaridad de coincidencias

In [258]:
def alpha(x_i, x_r):

    alpha = sum(x_i == x_r)

    return(alpha)   

In [259]:
Data_multiclass_numpy[2,:] 

array([2., 1., 3.])

In [260]:
Data_multiclass_numpy[5,:] 

array([2., 3., 3.])

In [261]:
alpha(x_i=Data_multiclass_numpy[2,:] , x_r=Data_multiclass_numpy[5,:])

2

In [262]:
Data_multiclass_numpy[15,:] 

array([2., 3., 2.])

In [263]:
Data_multiclass_numpy[14,:]

array([2., 4., 3.])

In [264]:
alpha(x_i=Data_multiclass_numpy[14,:] , x_r=Data_multiclass_numpy[15,:])

1

In [272]:
def matches_similarity(x_i, x_r, Data):

    p = Data.shape[1]

    matches_similarity = alpha(x_i, x_r) / p

    return(matches_similarity)

In [273]:
matches_similarity(x_i=Data_multiclass_numpy[2,:] , x_r=Data_multiclass_numpy[5,:], Data=Data_multiclass_numpy)

0.6666666666666666

In [274]:
matches_similarity(x_i=Data_multiclass_numpy[14,:] , x_r=Data_multiclass_numpy[15,:], Data=Data_multiclass_numpy)

0.3333333333333333

In [275]:
def Matrix_Sim_Matches(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))

   
    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                 M[i,r] = matches_similarity(x_i=Data[i,:], x_r=Data[r,:], Data=Data)
                      
    return M 

In [276]:
M_matches = Matrix_Sim_Matches(Data=Data_multiclass_numpy)

M_matches 

array([[1.        , 0.66666667, 0.33333333, ..., 0.33333333, 0.33333333,
        0.        ],
       [0.        , 1.        , 0.66666667, ..., 0.33333333, 0.33333333,
        0.33333333],
       [0.        , 0.        , 1.        , ..., 0.33333333, 0.33333333,
        0.33333333],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.66666667,
        0.33333333],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.33333333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [277]:
M_matches = M_matches + M_matches.T - np.diag(np.repeat(1 , len(M_matches)), k=0)

M_matches

array([[1.        , 0.66666667, 0.33333333, ..., 0.33333333, 0.33333333,
        0.        ],
       [0.66666667, 1.        , 0.66666667, ..., 0.33333333, 0.33333333,
        0.33333333],
       [0.33333333, 0.66666667, 1.        , ..., 0.33333333, 0.33333333,
        0.33333333],
       ...,
       [0.33333333, 0.33333333, 0.33333333, ..., 1.        , 0.66666667,
        0.33333333],
       [0.33333333, 0.33333333, 0.33333333, ..., 0.66666667, 1.        ,
        0.33333333],
       [0.        , 0.33333333, 0.33333333, ..., 0.33333333, 0.33333333,
        1.        ]])

In [278]:
def Dist_Matches(x_i, x_r, Data):

    Dist_Matches = np.sqrt(matches_similarity(x_i, x_i, Data) +  matches_similarity(x_r, x_r, Data) - 2*matches_similarity(x_i, x_r, Data) )

    return( Dist_Matches )

In [279]:
matches_similarity(x_i=Data_multiclass_numpy[2,:] , x_r=Data_multiclass_numpy[5,:], Data=Data_multiclass_numpy)

0.6666666666666666

In [280]:
def Matrix_Dist_Matches(Data):

    # Paso previo necesario si Data es pd.DataFrame  -->  Data = Data.to_numpy()

    n = len(Data)

    M =  np.empty((n , n))
   
    for i in range(0, n):

         for r in range(0, n):

             if i >= r :
               
                M[i,r] = 0

             else :

                M[i,r] = Dist_Matches(x_i=Data[i,:], x_r=Data[r,:], Data=Data)
                      
    return M 

In [281]:
M_Dist_Matches = Matrix_Dist_Matches(Data=Data_multiclass_numpy)

M_Dist_Matches

array([[0.        , 0.81649658, 1.15470054, ..., 1.15470054, 1.15470054,
        1.41421356],
       [0.        , 0.        , 0.81649658, ..., 1.15470054, 1.15470054,
        1.15470054],
       [0.        , 0.        , 0.        , ..., 1.15470054, 1.15470054,
        1.15470054],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.81649658,
        1.15470054],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.15470054],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [282]:
M_Dist_Matches = M_Dist_Matches + M_Dist_Matches.T

M_Dist_Matches

array([[0.        , 0.81649658, 1.15470054, ..., 1.15470054, 1.15470054,
        1.41421356],
       [0.81649658, 0.        , 0.81649658, ..., 1.15470054, 1.15470054,
        1.15470054],
       [1.15470054, 0.81649658, 0.        , ..., 1.15470054, 1.15470054,
        1.15470054],
       ...,
       [1.15470054, 1.15470054, 1.15470054, ..., 0.        , 0.81649658,
        1.15470054],
       [1.15470054, 1.15470054, 1.15470054, ..., 0.81649658, 0.        ,
        1.15470054],
       [1.41421356, 1.15470054, 1.15470054, ..., 1.15470054, 1.15470054,
        0.        ]])

## Similaridad de Gower

In [283]:
def Matrix_Gower_Similarity(Data, p1, p2, p3 ):

    n = len(Data)

    M =  np.empty((n , n))

############################################################
    
    G_vector = np.repeat(0.5, p1)

    for k in range(0, p1):

        G_vector[k] = Data[:,k].max() - Data[:,k].min()

############################################################
   
    ones = np.repeat(1, p1)

    Quant_Data = Data[: , 0:p1]

    Binary_Data = Data[: , (p1):(p1+p2)]

    Multiple_Data = Data[: , (p1+p2):(p1+p2+p3) ]

############################################################

    a, b, c, d, p = a_b_c_d_Matrix(Binary_Data)

############################################################

    for i in range(0, n):

         for r in range(0, n):

            if i > r :
               
                 M[i,r] = 0
            
            elif i == r :
               
                 M[i,r] = 1
            
            else :

                # Calculo de la distancia de Gower entre las observaciones x_i y x_r

                numerator_part_1 = ( ones - ( abs(Quant_Data[i,:] - Quant_Data[r,:]) / G_vector ) ).sum() 

                numerator_part_2 = a[i,r] + alpha(Multiple_Data[i,:], Multiple_Data[r,:])

                numerator = numerator_part_1 + numerator_part_2
 
                denominator = p1 + (p2 - d[i,r]) + p3

                M[i,r] = numerator / denominator
                      
   
    return M  

In [284]:
M_Gower = Matrix_Gower_Similarity(Data=Data_mixed_numpy, p1=6, p2=4, p3=3)

M_Gower

array([[1.        , 0.86928447, 0.61234779, ..., 0.61200705, 0.68768535,
        0.67882015],
       [0.        , 1.        , 0.72440439, ..., 0.63958297, 0.66860788,
        0.75783494],
       [0.        , 0.        , 1.        , ..., 0.63993289, 0.54854692,
        0.61639629],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.65208854,
        0.5993045 ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.70693976],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [285]:
M_Gower = M_Gower  + M_Gower.T - np.diag(np.repeat(1 , len(M_Gower)), k=0)

M_Gower

array([[1.        , 0.86928447, 0.61234779, ..., 0.61200705, 0.68768535,
        0.67882015],
       [0.86928447, 1.        , 0.72440439, ..., 0.63958297, 0.66860788,
        0.75783494],
       [0.61234779, 0.72440439, 1.        , ..., 0.63993289, 0.54854692,
        0.61639629],
       ...,
       [0.61200705, 0.63958297, 0.63993289, ..., 1.        , 0.65208854,
        0.5993045 ],
       [0.68768535, 0.66860788, 0.54854692, ..., 0.65208854, 1.        ,
        0.70693976],
       [0.67882015, 0.75783494, 0.61639629, ..., 0.5993045 , 0.70693976,
        1.        ]])

In [286]:
def Matrix_Gower_Distance(Data, p1, p2, p3 ):

    M = Matrix_Gower_Similarity(Data, p1, p2, p3)

    M = M + M.T - np.diag(np.repeat(1 , len(M)), k=0)

    M = np.sqrt( 1 - M )

    return M

In [287]:
M_Gower_Dist = Matrix_Gower_Distance(Data=Data_mixed_numpy, p1=6, p2=4, p3=3)

M_Gower_Dist

array([[0.        , 0.36154603, 0.62261723, ..., 0.6228908 , 0.55885118,
        0.56672731],
       [0.36154603, 0.        , 0.52497201, ..., 0.60034742, 0.57566667,
        0.4921027 ],
       [0.62261723, 0.52497201, 0.        , ..., 0.60005592, 0.67190258,
        0.6193575 ],
       ...,
       [0.6228908 , 0.60034742, 0.60005592, ..., 0.        , 0.5898402 ,
        0.63300514],
       [0.55885118, 0.57566667, 0.67190258, ..., 0.5898402 , 0.        ,
        0.54135038],
       [0.56672731, 0.4921027 , 0.6193575 , ..., 0.63300514, 0.54135038,
        0.        ]])

### Comparacion con los resultados obtenidos con la funcion Gower2.m de Aurea  --> se obtienen los mismos resultados !!

In [288]:
futbol = pd.read_csv('jugadores_futbol.csv')

futbol_np = futbol.to_numpy()

In [289]:
M_Gower_futbol = Matrix_Gower_Similarity(Data=futbol_np, p1=4, p2=1, p3=2)

In [290]:
M_Gower_futbol = M_Gower_futbol  + M_Gower_futbol.T - np.diag(np.repeat(1 , len(M_Gower_futbol)), k=0)

M_Gower_futbol

array([[1.        , 0.63275613, 0.45075758, ..., 0.41684704, 0.61201299,
        0.39303752],
       [0.63275613, 1.        , 0.43076599, ..., 0.49810606, 0.64920034,
        0.47032828],
       [0.45075758, 0.43076599, 1.        , ..., 0.63720539, 0.7260101 ,
        0.60942761],
       ...,
       [0.41684704, 0.49810606, 0.63720539, ..., 1.        , 0.67508418,
        0.91666667],
       [0.61201299, 0.64920034, 0.7260101 , ..., 0.67508418, 1.        ,
        0.6473064 ],
       [0.39303752, 0.47032828, 0.60942761, ..., 0.91666667, 0.6473064 ,
        1.        ]])

In [291]:
M_Gower_futbol[0:8, 0:8]

array([[1.        , 0.63275613, 0.45075758, 0.38870851, 0.42676768,
        0.61471861, 0.56349206, 0.42839105],
       [0.63275613, 1.        , 0.43076599, 0.37689394, 0.46338384,
        0.44660895, 0.5256734 , 0.43244949],
       [0.45075758, 0.43076599, 1.        , 0.58038721, 0.64877946,
        0.58928571, 0.34995791, 0.52946128],
       [0.38870851, 0.37689394, 0.58038721, 1.        , 0.5625    ,
        0.52723665, 0.27756734, 0.625     ],
       [0.42676768, 0.46338384, 0.64877946, 0.5625    , 1.        ,
        0.77236652, 0.46506734, 0.6875    ],
       [0.61471861, 0.44660895, 0.58928571, 0.52723665, 0.77236652,
        1.        , 0.42496392, 0.63834776],
       [0.56349206, 0.5256734 , 0.34995791, 0.27756734, 0.46506734,
        0.42496392, 1.        , 0.42571549],
       [0.42839105, 0.43244949, 0.52946128, 0.625     , 0.6875    ,
        0.63834776, 0.42571549, 1.        ]])

Primeras 8 filas y 8 columnas obtenidas al aplicar Gower2.m de Aurea para la matriz de similaridades de Gower 
 

         0    0.3672    0.5492    0.6113    0.5732    0.3853    0.4365    0.5716
    0.3672         0    0.5692    0.6231    0.5366    0.5534    0.4743    0.5676
    0.5492    0.5692         0    0.4196    0.3512    0.4107    0.6500    0.4705
    0.6113    0.6231    0.4196         0    0.4375    0.4728    0.7224    0.3750
    0.5732    0.5366    0.3512    0.4375         0    0.2276    0.5349    0.3125
    0.3853    0.5534    0.4107    0.4728    0.2276         0    0.5750    0.3617
    0.4365    0.4743    0.6500    0.7224    0.5349    0.5750         0    0.5743
    0.5716    0.5676    0.4705    0.3750    0.3125    0.3617    0.5743         0



In [292]:
M_Gower_Dist_futbol = Matrix_Gower_Distance(Data=futbol_np, p1=4, p2=1, p3=2)

M_Gower_Dist_futbol

array([[0.        , 0.60600649, 0.74110892, ..., 0.76364452, 0.62288604,
        0.77907797],
       [0.60600649, 0.        , 0.75447598, ..., 0.70844473, 0.59228343,
        0.72778549],
       [0.74110892, 0.75447598, 0.        , ..., 0.60232434, 0.52344044,
        0.62495791],
       ...,
       [0.76364452, 0.70844473, 0.60232434, ..., 0.        , 0.57001388,
        0.28867513],
       [0.62288604, 0.59228343, 0.52344044, ..., 0.57001388, 0.        ,
        0.59388012],
       [0.77907797, 0.72778549, 0.62495791, ..., 0.28867513, 0.59388012,
        0.        ]])

In [293]:
M_Gower_Dist_futbol[0:8 , 0:8]**2

array([[0.        , 0.36724387, 0.54924242, 0.61129149, 0.57323232,
        0.38528139, 0.43650794, 0.57160895],
       [0.36724387, 0.        , 0.56923401, 0.62310606, 0.53661616,
        0.55339105, 0.4743266 , 0.56755051],
       [0.54924242, 0.56923401, 0.        , 0.41961279, 0.35122054,
        0.41071429, 0.65004209, 0.47053872],
       [0.61129149, 0.62310606, 0.41961279, 0.        , 0.4375    ,
        0.47276335, 0.72243266, 0.375     ],
       [0.57323232, 0.53661616, 0.35122054, 0.4375    , 0.        ,
        0.22763348, 0.53493266, 0.3125    ],
       [0.38528139, 0.55339105, 0.41071429, 0.47276335, 0.22763348,
        0.        , 0.57503608, 0.36165224],
       [0.43650794, 0.4743266 , 0.65004209, 0.72243266, 0.53493266,
        0.57503608, 0.        , 0.57428451],
       [0.57160895, 0.56755051, 0.47053872, 0.375     , 0.3125    ,
        0.36165224, 0.57428451, 0.        ]])

 Primeras 8 filas y 8 columnas obtenidas con la funcion Gower2.m de Aurea para la matriz de cuadrados de distancias de Gower
  
         0    0.3672    0.5492    0.6113    0.5732    0.3853    0.4365    0.5716
    0.3672         0    0.5692    0.6231    0.5366    0.5534    0.4743    0.5676
    0.5492    0.5692         0    0.4196    0.3512    0.4107    0.6500    0.4705
    0.6113    0.6231    0.4196         0    0.4375    0.4728    0.7224    0.3750
    0.5732    0.5366    0.3512    0.4375         0    0.2276    0.5349    0.3125
    0.3853    0.5534    0.4107    0.4728    0.2276         0    0.5750    0.3617
    0.4365    0.4743    0.6500    0.7224    0.5349    0.5750         0    0.5743
    0.5716    0.5676    0.4705    0.3750    0.3125    0.3617    0.5743         0



### Comparacion con lo que se obtiene al usar el paquete Gower  --> No se obtienen los mismos resultados.

In [294]:
import gower

M_Dist_cuadrados_Gower_futbol_Paquete = gower.gower_matrix(futbol_np, cat_features=[False,False,False,False,True,True,True])

M_Dist_cuadrados_Gower_futbol_Paquete[0:8 , 0:8]

array([[0.        , 0.36724386, 0.54924244, 0.61129147, 0.57323235,
        0.38528138, 0.43650794, 0.57160896],
       [0.36724386, 0.        , 0.48791486, 0.53409094, 0.4599567 ,
        0.55339104, 0.40656567, 0.48647186],
       [0.54924244, 0.48791486, 0.        , 0.3596681 , 0.3010462 ,
        0.4107143 , 0.5571789 , 0.4033189 ],
       [0.61129147, 0.53409094, 0.3596681 , 0.        , 0.375     ,
        0.47276336, 0.619228  , 0.32142857],
       [0.57323235, 0.4599567 , 0.3010462 , 0.375     , 0.        ,
        0.22763348, 0.4585137 , 0.26785713],
       [0.38528138, 0.55339104, 0.4107143 , 0.47276336, 0.22763348,
        0.        , 0.5750361 , 0.36165223],
       [0.43650794, 0.40656567, 0.5571789 , 0.619228  , 0.4585137 ,
        0.5750361 , 0.        , 0.4922439 ],
       [0.57160896, 0.48647186, 0.4033189 , 0.32142857, 0.26785713,
        0.36165223, 0.4922439 , 0.        ]], dtype=float32)

 Primeras 8 filas y 8 columnas obtenidas con la funcion Gower2.m de Aurea para la matriz de cuadrados de distancias de Gower
  
         0    0.3672    0.5492    0.6113    0.5732    0.3853    0.4365    0.5716
    0.3672         0    0.5692    0.6231    0.5366    0.5534    0.4743    0.5676
    0.5492    0.5692         0    0.4196    0.3512    0.4107    0.6500    0.4705
    0.6113    0.6231    0.4196         0    0.4375    0.4728    0.7224    0.3750
    0.5732    0.5366    0.3512    0.4375         0    0.2276    0.5349    0.3125
    0.3853    0.5534    0.4107    0.4728    0.2276         0    0.5750    0.3617
    0.4365    0.4743    0.6500    0.7224    0.5349    0.5750         0    0.5743
    0.5716    0.5676    0.4705    0.3750    0.3125    0.3617    0.5743         0



La primera fila si coincide, pero hay otras como la ultima que no coinciden. Deben usar otra version de l similaridad de Gower u otra transformacion de similaridad a distancia.