# Optimizando código en `Python`

Vamos a ilustrar como paralelizar bucles for en Python con un ejemplo:

La idea es paralelizar el siguiente algoritmo KNN para clasificacion basado en la distancia de Gower-BQ (una variante de la distancia de Gower aplicable a conjunto de datos binarios-cuantitativos).

Aqui lo importante no es el funcionamiento del algoritmo en si, si no que hay una parte de este que genera unos costes computacionales altos, lo que se traduce en que al aplicar el algoritmo a un data-set de 5000 variables, este tarde mas de 13 minutos en compilarse por completo. La idea de paralelizarlo es reducir este tiempo de cómputo, para asi hacerlo mas aplicable en contextos reales.

El algoritmo original (sin paralelizar):

In [1]:
import pandas as pd
import numpy as np

In [2]:
def KNN_classification( X , Y , x_new, k, distance = "Gower-BQ" ,  p1=0, p2=0 ):

 
####################################################################################################################################################################################################################################################

    X = pd.concat([X, x_new.to_frame().T], ignore_index=True)

    distances = []

    groups_knn = []

######################################################################################################################################


    if distance == "Gower-BQ":

        def a(Binary_Data) :

            X = Binary_Data

            a = X @ X.T

            return(a)

##########################################################################################

        def d(Binary_Data):

            X = Binary_Data

            ones_matrix = np.ones(( X.shape[0] , X.shape[1])) 

            d = (ones_matrix - X) @ (ones_matrix - X).T

            return(d)

##########################################################################################

        def GowerBQ_Similarity_Python(i,j, BQ_Data_Set, p1, p2):

            X = BQ_Data_Set

   # The data matrix X have to be order in the following way:
   # The p1 first are quantitative, the following p2 are binary categorical 

##########################################################################################
            def G(k, X):

                range = X.iloc[:,k].max() - X.iloc[:,k].min() 

                return(range)

            G_vector = np.repeat(0, p1)

            for r in range(0, p1): 

                G_vector[r] = G(r, X)
##########################################################################################
    
            ones = np.repeat(1, p1)

            Quantitative_Data = X.iloc[: , 0:p1]

            Binary_Data = X.iloc[: , (p1):(p1+p2)]
         
 
##########################################################################################

            numerator_part_1 = ( ones - ( (Quantitative_Data.iloc[i-1,:] - Quantitative_Data.iloc[j-1,:]).abs() / G_vector ) ).sum() 

            numerator_part_2 = a(Binary_Data).iloc[i-1,j-1] 
     
            numerator = numerator_part_1 + numerator_part_2

            denominator = p1 + (p2 - d(Binary_Data).iloc[i-1,j-1])  

            Similarity_Gower = numerator / denominator  

            return(Similarity_Gower)

##########################################################################################


        def Dist_GowerBQ_Py(i, j, BQ_Data ,  p1, p2):

            Dist_Gower = np.sqrt( 1 - GowerBQ_Similarity_Python(i, j, BQ_Data , p1, p2) )

            return(Dist_Gower)

##########################################################################################

        for i in range(1, len(X)):

            distances.append( Dist_GowerBQ_Py( len(X), i , X, p1, p2) )


######################################################################################################################################

######################################################################################################################################
    
    distances = pd.DataFrame({'distances': distances})

    distances = distances.sort_values(by=["distances"]).reset_index(drop=False)
        
    knn = distances.iloc[0:k , :]

    for i in knn.iloc[:,0]:

        groups_knn.append(Y.iloc[i,:])

    unique, counts = np.unique(groups_knn , return_counts=True)

    unique_Y , counts_Y = np.unique(Y , return_counts=True)

    if len(unique) == len(unique_Y) :

        proportions_groups_knn = pd.DataFrame({'proportions_groups': counts/k, 'groups': unique_Y })
    
    elif len(unique) < len(unique_Y) :

        proportions_groups_knn = pd.DataFrame({'proportions_groups': counts/k, 'groups': unique })



    prediction_group = proportions_groups_knn.sort_values(by=["proportions_groups"], ascending=False).iloc[0,:]['groups']

    message = print( "x_new is classify in the group", prediction_group , ". So KNN algorithm predict y_new =",  prediction_group )                                      
                                       

    return proportions_groups_knn , message  

Vamos a probar el algoritmo con un mismo data-set pero con distintos tamaños de filas (observaciones).

Preparamos los datos para la prueba:

In [3]:
Gender_classification = pd.read_csv('gender_classification.csv')

x_new = pd.Series({'long_hair': 1, 'forehead_width_cm': 4, 'forehead_height_cm': 6, 'nose_wide': 1 , 'nose_long': 1 , 'nose_long': 1 , 'lips_thin':1, 'distance_nose_to_lip_long': 1 })

Y = Gender_classification.loc[: , ['gender']]

from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()

Y['gender'] = ord_enc.fit_transform(Y[['gender']])

X = Gender_classification.loc[: , ['forehead_width_cm', 'forehead_height_cm',   # Quantitative (2)

                   'long_hair', 'nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long'     # Binary (5)
                 
                            ]] 


In [4]:
X_small_1 = X.iloc[0:1000,:]
Y_small_1 = Y.iloc[0:1000,:]

X_small_2 = X.iloc[0:2000,:]
Y_small_2 = Y.iloc[0:2000,:]

X_small_3 = X.iloc[0:3000,:]
Y_small_3 = Y.iloc[0:3000,:]

In [5]:
KNN_classification( X_small_1 , Y_small_1  , x_new, 5 , distance = "Gower-BQ" , p1=2, p2=5 )

x_new is classify in the group 1.0 . So KNN algorithm predict y_new = 1.0


(   proportions_groups  groups
 0                 1.0     1.0,
 None)

20seg / 27seg / 26.8seg

In [6]:
KNN_classification( X_small_2 , Y_small_2  , x_new, 5 , distance = "Gower-BQ" , p1=2, p2=5 )

x_new is classify in the group 1.0 . So KNN algorithm predict y_new = 1.0


(   proportions_groups  groups
 0                 1.0     1.0,
 None)

2.47min  / 2.35 / 2.29min

In [7]:
KNN_classification( X_small_3 , Y_small_3  , x_new, 5 , distance = "Gower-BQ" , p1=2, p2=5 )

x_new is classify in the group 1.0 . So KNN algorithm predict y_new = 1.0


(   proportions_groups  groups
 0                 1.0     1.0,
 None)

8.51min , 8.38min

In [16]:
KNN_classification( X , Y  , x_new, 5 , distance = "Gower-BQ" , p1=2, p2=5 )

x_new is classify in the group 1.0 . So KNN algorithm predict y_new = 1.0


(   proportions_groups  groups
 0                 1.0     1.0,
 None)

38.48min

In [9]:
from joblib import Parallel, delayed
import multiprocessing


In [11]:
def KNN_classification_parallel( X , Y , x_new, k, distance = "Gower-BQ" ,  p1=0, p2=0 ):

 
####################################################################################################################################################################################################################################################

    X = pd.concat([X, x_new.to_frame().T], ignore_index=True)

    distances = []

    groups_knn = []

######################################################################################################################################


    if distance == "Gower-BQ":

        def a(Binary_Data) :

            X = Binary_Data

            a = X @ X.T

            return(a)

##########################################################################################

        def d(Binary_Data):

            X = Binary_Data

            ones_matrix = np.ones(( X.shape[0] , X.shape[1])) 

            d = (ones_matrix - X) @ (ones_matrix - X).T

            return(d)

##########################################################################################

        def GowerBQ_Similarity_Python(i,j, BQ_Data_Set, p1, p2):

            X = BQ_Data_Set

   # The data matrix X have to be order in the following way:
   # The p1 first are quantitative, the following p2 are binary categorical 

##########################################################################################
            def G(k, X):

                range = X.iloc[:,k].max() - X.iloc[:,k].min() 

                return(range)

            G_vector = np.repeat(0, p1)

            for r in range(0, p1): 

                G_vector[r] = G(r, X)
##########################################################################################
    
            ones = np.repeat(1, p1)

            Quantitative_Data = X.iloc[: , 0:p1]

            Binary_Data = X.iloc[: , (p1):(p1+p2)]
         
 
##########################################################################################

            numerator_part_1 = ( ones - ( (Quantitative_Data.iloc[i-1,:] - Quantitative_Data.iloc[j-1,:]).abs() / G_vector ) ).sum() 

            numerator_part_2 = a(Binary_Data).iloc[i-1,j-1] 
     
            numerator = numerator_part_1 + numerator_part_2

            denominator = p1 + (p2 - d(Binary_Data).iloc[i-1,j-1])  

            Similarity_Gower = numerator / denominator  

            return(Similarity_Gower)

##########################################################################################

        def Dist_GowerBQ_Py(i, j, BQ_Data ,  p1, p2):

            Dist_Gower = np.sqrt( 1 - GowerBQ_Similarity_Python(i, j, BQ_Data , p1, p2) )

            return(Dist_Gower)

##########################################################################################

# ESTA ES LA PARTE CRITICA DEL ALGORITMO, LA QUE LO HACE LENTO. ESTE BUCLE FOR ES EL QUE DEBEMOS PARALELIZAR.


        # for i in range(1, len(X)):

           # distances.append( Dist_GowerBQ_Py( len(X), i , X, p1, p2) )

        n_jobs  = multiprocessing.cpu_count()


        distances = Parallel(n_jobs=n_jobs)( delayed(Dist_GowerBQ_Py)( len(X), i , X, p1, p2) for i in range(1, len(X)) )


######################################################################################################################################

######################################################################################################################################
    
    distances = pd.DataFrame({'distances': distances})

    distances = distances.sort_values(by=["distances"]).reset_index(drop=False)
        
    knn = distances.iloc[0:k , :]

    for i in knn.iloc[:,0]:

        groups_knn.append(Y.iloc[i,:])

    unique, counts = np.unique(groups_knn , return_counts=True)

    unique_Y , counts_Y = np.unique(Y , return_counts=True)

    if len(unique) == len(unique_Y) :

        proportions_groups_knn = pd.DataFrame({'proportions_groups': counts/k, 'groups': unique_Y })
    
    elif len(unique) < len(unique_Y) :

        proportions_groups_knn = pd.DataFrame({'proportions_groups': counts/k, 'groups': unique })



    prediction_group = proportions_groups_knn.sort_values(by=["proportions_groups"], ascending=False).iloc[0,:]['groups']

    message = print( "x_new is classify in the group", prediction_group , ". So KNN algorithm predict y_new =",  prediction_group )                                      
                                       

    return proportions_groups_knn , message  

Probamos ahora el algoritmo paralelizado con los mismos ejemplos que antes:

In [12]:
KNN_classification_parallel( X_small_1 , Y_small_1  , x_new, 5 , distance = "Gower-BQ" , p1=2, p2=5 )

x_new is classify in the group 1.0 . So KNN algorithm predict y_new = 1.0


(   proportions_groups  groups
 0                 1.0     1.0,
 None)

15.5 seg , 16.3seg

In [13]:
KNN_classification_parallel( X_small_2 , Y_small_2  , x_new, 5 , distance = "Gower-BQ" , p1=2, p2=5 )

x_new is classify in the group 1.0 . So KNN algorithm predict y_new = 1.0


(   proportions_groups  groups
 0                 1.0     1.0,
 None)

1min , 1.03min

In [14]:
KNN_classification_parallel( X_small_3 , Y_small_3  , x_new, 5 , distance = "Gower-BQ" , p1=2, p2=5 )

x_new is classify in the group 1.0 . So KNN algorithm predict y_new = 1.0


(   proportions_groups  groups
 0                 1.0     1.0,
 None)

3.33min , 3.17min

In [15]:
KNN_classification_parallel( X , Y  , x_new, 5 , distance = "Gower-BQ" , p1=2, p2=5 )

x_new is classify in the group 1.0 . So KNN algorithm predict y_new = 1.0


(   proportions_groups  groups
 0                 1.0     1.0,
 None)

14.56min

La funcion KNN_classification original tarda mas de 25 mins en hacer validacion cruzada sumple con un set de train de 1000 observaciones. Hay que paralelozarla para hacer viable cross validation con ella !

---

### Codigo sin optimizar:

La justificacion principal de optimizar nuestros codigos en ciencia de datos, poder implementar procedimientos en caso reales que exigen un alto rendimiento computacional.

Si para ejecutar un procedimiento en un caso real el ordenador tarda horas, dias o es incluso intratable computacionalemente, directamente no podremos aplicar dicho procedimiento (por bueno que sea) en casos reales, y tendremos que limitarnos a usar procedimientos quiza peores desde un punto de vista estadistico, pero mejores a nivel de coste computacional.

La idea de optimizar codigo es no tener que desechar buenos procedimientos a nivel estadistico porque sean malos a nivel computacional (sean ineficientes computacionalmente), la idea es hacerlos mas eficientes, para reducir sus costes de computacion.

El siguiente codigo es el que usaremos como ejemplo a lo largo de este articulo, la idea es medir su rendimiento original y posteriormente aplicarle diferentes tecnicas para optimizarlo y ver como cambia su rendimiento.

In [1]:
import pandas as pd
import numpy as np

La siguiente funcion es una implementacion de KNN para regresion usando la distancia de Gower, que es una metrica computacionalmente muy costosa.

La idea es usar la funcion KNN_regresion dentro de una rutina de validacion cruzada, como ejemplo de procedimiento que supone un alto coste computacional.

In [2]:
def KNN_regression( X , Y , x_new, k, distance = "Minkowski" , q = 0, p1=0, p2=0, p3=0 ):

   
####################################################################################################################################################################################################################################################

    # Y tiene que ser una variable respuesta cuantitativa

    # X tiene que ser un panda data frame con los predictotres (X1,...,Xp). 

    # x_new tiene que ser un vector. 

####################################################################################################################################################################################################################################################

    X = pd.concat([X, x_new.to_frame().T], ignore_index=True)

    distances = []

    Y_values_knn = []


####################################################################################################################################################################################################################################################
    
    
    
    if distance == "Gower":

        # The data matrix X have to be order in the following way:
        # The p1 first are quantitative, the following p2 are binary categorical, and the following p3 are multiple categorical.


        def a(Binary_Data) :

            X = Binary_Data

            a = X @ X.T

            return(a)

##########################################################################################

        def d(Binary_Data):

            X = Binary_Data

            ones_matrix = np.ones(( X.shape[0] , X.shape[1])) 

            d = (ones_matrix - X) @ (ones_matrix - X).T

            return(d)

##########################################################################################

        def alpha_py(i,j, Multiple_Categorical_Data):

                X = Multiple_Categorical_Data

                alpha = np.repeat(0, X.shape[1])

                for k in range(0, X.shape[1]) :

                    if X.iloc[i-1, k] == X.iloc[j-1, k] :

                        alpha[k] = 1

                    else :

                        alpha[k] = 0


                alpha = alpha.sum()

                return(alpha)

   ##########################################################################################


        def Gower_Similarity_Python(i,j, Mixed_Data_Set, p1, p2, p3):

            X = Mixed_Data_Set

   # The data matrix X have to be order in the following way:
   # The p1 first are quantitative, the following p2 are binary categorical, and the following p3 are multiple categorical.

   #####################################################################################
        
            def G(k, X):

                range = X.iloc[:,k].max() - X.iloc[:,k].min() 

                return(range)

            G_vector = np.repeat(0.5, p1)

            for r in range(0, p1):

                G_vector[r] = G(r, X)
                
      
    ##########################################################################################
    
            ones = np.repeat(1, p1)

            Quantitative_Data = X.iloc[: , 0:p1]

            Binary_Data = X.iloc[: , (p1):(p1+p2)]
            
            Multiple_Categorical_Data = X.iloc[: , (p1+p2):(p1+p2+p3) ]

    ##########################################################################################

            numerator_part_1 = ( ones - ( (Quantitative_Data.iloc[i-1,:] - Quantitative_Data.iloc[j-1,:]).abs() / G_vector ) ).sum() 

            numerator_part_2 = a(Binary_Data).iloc[i-1,j-1] + alpha_py(i,j, Multiple_Categorical_Data)

            numerator = numerator_part_1 + numerator_part_2
 
            denominator = p1 + (p2 - d(Binary_Data).iloc[i-1,j-1]) + p3

            Similarity_Gower = numerator / denominator  

            return(Similarity_Gower)

##########################################################################################

        def Dist_Gower_Py(i, j, Mixed_Data , p1, p2, p3):

            Dist_Gower = np.sqrt( 1 - Gower_Similarity_Python(i, j, Mixed_Data , p1, p2, p3) )

            return(Dist_Gower)    

    ###################################################################

        for i in range(1, len(X)):

            distances.append( Dist_Gower_Py( len(X), i , X, p1, p2, p3) )

        
######################################################################################################################################
    
    distances = pd.DataFrame({'distances': distances})

    distances = distances.sort_values(by=["distances"]).reset_index(drop=False)
        
    knn = distances.iloc[0:k , :]

    for i in knn.iloc[:,0]:

        Y_values_knn.append(Y.iloc[i , ])


    y_predict = sum(Y_values_knn)/k


                                     
    return y_predict   

Cargamos los datos con los que haremos las pruebas:

In [4]:
House_Prices_Data = pd.read_csv('House_Price_Regression.csv')

House_Prices_Data = House_Prices_Data.loc[:, ['price', 'size_in_m_2', 'no_of_bedrooms', 'no_of_bathrooms', 'quality_recode', 'latitude', 'private_garden_recode', 'private_pool_recode', 'longitude']]

House_Prices_Data['quality_recode'] = House_Prices_Data['quality_recode'].astype('object')
House_Prices_Data['private_garden_recode'] = House_Prices_Data['private_garden_recode'].astype('object')
House_Prices_Data['private_pool_recode'] = House_Prices_Data['private_pool_recode'].astype('object')

House_Prices_Data = House_Prices_Data.rename({'price': 'Y'}, axis=1)

In [5]:
Data_Houses_Prices_Train = House_Prices_Data.sample(frac=0.8, replace=False, weights=None, random_state=555, axis=None, ignore_index=True)

Data_Houses_Prices_Test = House_Prices_Data.drop( Data_Houses_Prices_Train.index , )

X_train = Data_Houses_Prices_Train.loc[: , ['size_in_m_2', 'no_of_bedrooms', 'no_of_bathrooms','latitude', 'longitude', 'private_garden_recode', 'private_pool_recode',  'quality_recode']]

Y_train = Data_Houses_Prices_Train.loc[: , 'Y']

In [6]:
x_new = Data_Houses_Prices_Test.iloc[ 1 , range(1, Data_Houses_Prices_Test.shape[1])]

In [9]:
X_train_small = X_train.iloc[0:100]
Y_train_small = Y_train.iloc[0:100]

In [10]:
KNN_regression( X_train_small  , Y_train_small , x_new, k=10, distance = "Gower" , p1=5, p2=2, p3=1  )

1526288.8

La siguiente rutina de validacion simple usando la funcion KNN_regression es la que usaremos como ejemplo a lo largo de este artuiculo, ahora podremos ver cuanto tarda en ejecutarse con el algoritmo original sin haber sido optimizado de ningun modo, despues repetiremos el proceso habiendo optimizado el algoritmo con diferentes procedimientos:

In [9]:
def validacion_simple(Data_Test, X_train, Y_train):

    ##########################

    def prediction(i, Data_Test, X_train, Y_train ):

     x_new = Data_Test.iloc[ i , range(1, Data_Test.shape[1])]
 
     y_new_predict = KNN_regression( X_train  , Y_train , x_new, k=10, distance = "Gower" , p1=5, p2=2, p3=1  )

     return(y_new_predict)

    ##########################

    y_predictions_vector = []

    for i in  range(0, len(Data_Test)):

        y_new_predict = prediction(i, Data_Test, X_train, Y_train )

        y_predictions_vector.append( y_new_predict )

    ##########################

    ECM = ( (y_predictions_vector - Data_Test.loc[: , 'Y'])**2 ).sum() 

 
    return(y_predictions_vector , ECM)

In [59]:
y_predictions_vector, ECM = validacion_simple(Data_Houses_Prices_Test, X_train_small , Y_train_small)

In [60]:
ECM

3987208098987757.5

El tiempo de computacion usando solo las 100 primeras filas de X e Y es de  5.30 / 5.14 mins minutos

Si usasemos X e Y enteras (que tienen  1524 filas) el tiempo de computacion seria demasiado grande como para usar el algoritmo en la practica. 

---

### Paralelizacion de bucles for

Usaremos la libreria `joblib` para paralelizar los bucles for del algoritmo KNN_regression, tambien haremos lo mismo con el bloque de codigo con el que hacemos la validacion simple

In [28]:
def KNN_regression_Parallel( X , Y , x_new, k, distance = "Minkowski" , q = 0, p1=0, p2=0, p3=0 ):

##########################################################################################################

## Para paralelizar el algoritmo 

    from joblib import Parallel, delayed
    import multiprocessing

####################################################################################################################################################################################################################################################

    # Y tiene que ser una variable respuesta cuantitativa

    # X tiene que ser un panda data frame con los predictotres (X1,...,Xp). 

    # x_new tiene que ser un vector. 

####################################################################################################################################################################################################################################################

    X = pd.concat([X, x_new.to_frame().T], ignore_index=True)

    distances = []

    Y_values_knn = []


####################################################################################################################################################################################################################################################
    
    
    
    if distance == "Gower":

        # The data matrix X have to be order in the following way:
        # The p1 first are quantitative, the following p2 are binary categorical, and the following p3 are multiple categorical.


        def a(Binary_Data) :

            X = Binary_Data

            a = X @ X.T

            return(a)

##########################################################################################

        def d(Binary_Data):

            X = Binary_Data

            ones_matrix = np.ones(( X.shape[0] , X.shape[1])) 

            d = (ones_matrix - X) @ (ones_matrix - X).T

            return(d)

##########################################################################################

        def alpha_py(i,j, Multiple_Categorical_Data):

                X = Multiple_Categorical_Data

                alpha = np.repeat(0, X.shape[1])

                for k in range(0, X.shape[1]) :

                    if X.iloc[i-1, k] == X.iloc[j-1, k] :

                        alpha[k] = 1

                    else :

                        alpha[k] = 0


                alpha = alpha.sum()

                return(alpha)

   ##########################################################################################


        def Gower_Similarity_Python(i,j, Mixed_Data_Set, p1, p2, p3):

            X = Mixed_Data_Set

   # The data matrix X have to be order in the following way:
   # The p1 first are quantitative, the following p2 are binary categorical, and the following p3 are multiple categorical.

   #####################################################################################
        
            def G(k, X):

                range = X.iloc[:,k].max() - X.iloc[:,k].min() 

                return(range)

            G_vector = np.repeat(0.5, p1)

            for r in range(0, p1):

                G_vector[r] = G(r, X)
                
      
    ##########################################################################################
    
            ones = np.repeat(1, p1)

            Quantitative_Data = X.iloc[: , 0:p1]

            Binary_Data = X.iloc[: , (p1):(p1+p2)]
            
            Multiple_Categorical_Data = X.iloc[: , (p1+p2):(p1+p2+p3) ]

    ##########################################################################################

            numerator_part_1 = ( ones - ( (Quantitative_Data.iloc[i-1,:] - Quantitative_Data.iloc[j-1,:]).abs() / G_vector ) ).sum() 

            numerator_part_2 = a(Binary_Data).iloc[i-1,j-1] + alpha_py(i,j, Multiple_Categorical_Data)

            numerator = numerator_part_1 + numerator_part_2
 
            denominator = p1 + (p2 - d(Binary_Data).iloc[i-1,j-1]) + p3

            Similarity_Gower = numerator / denominator  

            return(Similarity_Gower)

##########################################################################################

        def Dist_Gower_Py(i, j, Mixed_Data , p1, p2, p3):

            Dist_Gower = np.sqrt( 1 - Gower_Similarity_Python(i, j, Mixed_Data , p1, p2, p3) )

            return(Dist_Gower)    

    ###################################################################

    ## PARTE DEL CODIGO A PARALELIZAR

        # for i in range(1, len(X)):

            # distances.append( Dist_Gower_Py( len(X), i , X, p1, p2, p3) )

        n_jobs  = multiprocessing.cpu_count()

        distances = Parallel(n_jobs=n_jobs)( delayed(Dist_Gower_Py)( len(X), i , X, p1, p2, p3) for i in range(1, len(X)) )

######################################################################################################################################
    
    distances = pd.DataFrame({'distances': distances})

    distances = distances.sort_values(by=["distances"]).reset_index(drop=False)
        
    knn = distances.iloc[0:k , :]

    for i in knn.iloc[:,0]:

        Y_values_knn.append(Y.iloc[i , ])


    y_predict = sum(Y_values_knn)/k


                                     
    return y_predict   

In [29]:
x_new = Data_Houses_Prices_Test.iloc[ 1 , range(1, Data_Houses_Prices_Test.shape[1])]

In [30]:
distances = KNN_regression_Parallel( X_train.iloc[0:100] , Y_train.iloc[0:100], x_new, k=10, distance = "Gower" , p1=5, p2=2, p3=1  )

In [36]:
distances = pd.DataFrame({'distances': distances})

In [39]:
distances

index  distances
0      36    0.73953
1       0        inf
2      71        inf
3      70        inf
4      69        inf
..    ...        ...
95     28        inf
96     27        inf
97     26        inf
98     24        inf
99     99        inf

[100 rows x 2 columns]

In [38]:
distances = distances.sort_values(by=["distances"]).reset_index(drop=False)

In [13]:
def validacion_simple_Parallel(Data_Test, X_train, Y_train):

    ##########################

    from joblib import Parallel, delayed
    import multiprocessing

    n_jobs  = multiprocessing.cpu_count()

    ##########################

    def prediction(i, Data_Test, X_train, Y_train ):

     x_new = Data_Test.iloc[ i , range(1,Data_Test.shape[1])]

     # Usamos KNN_regression_Parallel en vez de KNN_regression
 
     y_new_predict = KNN_regression_Parallel( X_train  , Y_train , x_new, k=10, distance = "Gower" , p1=5, p2=2, p3=1  )

     return(y_new_predict)

    ##########################

    y_predictions_vector = []

    # Paralelizamos el siguiente bucle for :

    # for i in  range(0, len(Data_Test)):

        # y_new_predict = prediction(i, Data_Test, X_train, Y_train )

        # y_predictions_vector.append( y_new_predict )

    
    y_predictions_vector = Parallel(n_jobs=n_jobs)( delayed(prediction)( i, Data_Test, X_train, Y_train) for i in range(0, len(Data_Test)) )

    #########################

    ECM = ( (y_predictions_vector - Data_Test.loc[: , 'Y'])**2 ).sum() 


    return(y_predictions_vector, ECM)

In [14]:
y_predictions_vector, ECM = validacion_simple_Parallel(Data_Houses_Prices_Test, X_train.iloc[0:100], Y_train.iloc[0:100])

NameError: name 'X' is not defined

In [54]:
ECM

3987208098987757.5

En este caso, tras paralelizar los algoritmos el tiempo de computacion se reduce de 5.30 mins a 1.42 mins , lo cual es bastante.

---

### Usar `Numpy` en vez de `Pandas`

In [1]:
def KNN_regression_Parallel_Numpy( X , Y , x_new, k, distance = "Minkowski" , q = 0, p1=0, p2=0, p3=0 ):

##########################################################################################################

## Para paralelizar el algoritmo 

    from joblib import Parallel, delayed
    import multiprocessing

    n_jobs  = multiprocessing.cpu_count()

####################################################################################################################################################################################################################################################

    # Y, X y x_new deben ser objetos Pandas ya que luego seran convertidos a objetos Numpy automaticamente por el algoritmo
    
    # Y tiene que ser un Pandas data frame con la variable respuesta 

    # X tiene que ser un Pandas data frame con los predictotres (X1,...,Xp). 

    # x_new tiene que ser un vector con una nueva observacion de los predictores. 

####################################################################################################################################################################################################################################################

    Y = Y.to_numpy()

    X = X.to_numpy() 

    x_new = x_new.to_numpy()

    X = np.concatenate((X, [x_new]), axis=0)


    distances = []

    Y_values_knn = []


####################################################################################################################################################################################################################################################
    
    
    
    if distance == "Gower":

        # The data matrix X have to be order in the following way:
        # The p1 first are quantitative, the following p2 are binary categorical, and the following p3 are multiple categorical.


        def a(Binary_Data) :

            X = Binary_Data

            a = X @ X.T

            return(a)

##########################################################################################

        def d(Binary_Data):

            X = Binary_Data

            ones_matrix = np.ones(( X.shape[0] , X.shape[1])) 

            d = (ones_matrix - X) @ (ones_matrix - X).T

            return(d)

##########################################################################################

        def alpha_py_Parallel(i,j, Multiple_Categorical_Data):

            X = Multiple_Categorical_Data

            alpha = np.repeat(0, X.shape[1])

            def argumento_bucle_for(k):

                if X[i-1, k] == X[j-1, k] :

                    alpha[k] = 1

                else :

                    alpha[k] = 0

                return(alpha) 
    
            alpha=Parallel(n_jobs=n_jobs)( delayed(argumento_bucle_for)( k ) for k in range(0, X.shape[1]) )
    
            alpha = sum(alpha)

            return(alpha)

##########################################################################################

        def Gower_Similarity_Python(i,j, Mixed_Data_Set, p1, p2, p3):

            X = Mixed_Data_Set

   # The data matrix X have to be order in the following way:
   # The p1 first are quantitative, the following p2 are binary categorical, and the following p3 are multiple categorical.

   #####################################################################################
        
            def G(k, X):

                range = X[:,k].max() - X[:,k].min() 

                return(range)

            G_vector = np.repeat(0, p1)

            for r in range(0, p1):

                G_vector[r] = G(r, X)
                
      
    ##########################################################################################
    
            ones = np.repeat(1, p1)

            Quantitative_Data = X[: , 0:p1]

            Binary_Data = X[: , (p1):(p1+p2)]
            
            Multiple_Categorical_Data = X[: , (p1+p2):(p1+p2+p3) ]

    ##########################################################################################

            numerator_part_1 = ( ones - ( abs(Quantitative_Data[i-1,:] - Quantitative_Data[j-1,:]) / G_vector ) ).sum() 

            numerator_part_2 = a(Binary_Data)[i-1,j-1] + alpha_py_Parallel(i,j, Multiple_Categorical_Data)

            numerator = numerator_part_1 + numerator_part_2
 
            denominator = p1 + (p2 - d(Binary_Data)[i-1,j-1]) + p3

            Similarity_Gower = numerator / denominator  

            return(Similarity_Gower)
  
##########################################################################################

        def Dist_Gower_Py(i, j, Mixed_Data , p1, p2, p3):

            Dist_Gower = np.sqrt( 1 - Gower_Similarity_Python(i, j, Mixed_Data , p1, p2, p3) )

            return(Dist_Gower)    

    ###################################################################

    ## PARTE DEL CODIGO A PARALELIZAR

        # for i in range(1, len(X)):

            # distances.append( Dist_Gower_Py( len(X), i , X, p1, p2, p3) )

        n_jobs  = multiprocessing.cpu_count()

        distances = Parallel(n_jobs=n_jobs)( delayed(Dist_Gower_Py)( len(X), i , X, p1, p2, p3) for i in range(1, len(X)) )

######################################################################################################################################
    
    distances = pd.DataFrame({'distances': distances})

    distances = distances.sort_values(by=["distances"]).reset_index(drop=False)
        
    knn = distances.iloc[0:k , :]

    for i in knn.iloc[:,0]:

        Y_values_knn.append(Y[i, ])


    y_predict = sum(Y_values_knn)/k

                                     
    return y_predict   

In [16]:
def KNN_regression_Parallel_Numpy( X , Y , x_new, k, distance = "Minkowski" , q = 0, p1=0, p2=0, p3=0 ):

##########################################################################################################

## Para paralelizar el algoritmo 

    from joblib import Parallel, delayed
    import multiprocessing

    n_jobs  = multiprocessing.cpu_count()

####################################################################################################################################################################################################################################################

    # Y, X y x_new deben ser objetos Pandas ya que luego seran convertidos a objetos Numpy automaticamente por el algoritmo
    
    # Y tiene que ser un Pandas data frame con la variable respuesta 

    # X tiene que ser un Pandas data frame con los predictotres (X1,...,Xp). 

    # x_new tiene que ser un vector con una nueva observacion de los predictores. 

####################################################################################################################################################################################################################################################

    Y = Y.to_numpy()

    X = X.to_numpy() 

    x_new = x_new.to_numpy()

    X = np.concatenate((X, [x_new]), axis=0)


    distances = []

    Y_values_knn = []


####################################################################################################################################################################################################################################################
    
    
    
    if distance == "Gower":

        # The data matrix X have to be order in the following way:
        # The p1 first are quantitative, the following p2 are binary categorical, and the following p3 are multiple categorical.


        def a(Binary_Data) :

            X = Binary_Data

            a = X @ X.T

            return(a)

##########################################################################################

        def d(Binary_Data):

            X = Binary_Data

            ones_matrix = np.ones(( X.shape[0] , X.shape[1])) 

            d = (ones_matrix - X) @ (ones_matrix - X).T

            return(d)

##########################################################################################

        def alpha_py_Parallel(i,j, Multiple_Categorical_Data):

            X = Multiple_Categorical_Data

            alpha = np.repeat(0, X.shape[1])

            def argumento_bucle_for(k):

                if X[i-1, k] == X[j-1, k] :

                    alpha[k] = 1

                else :

                    alpha[k] = 0

                return(alpha) 
    
            alpha=Parallel(n_jobs=n_jobs)( delayed(argumento_bucle_for)( k ) for k in range(0, X.shape[1]) )
    
            alpha = sum(alpha)

            return(alpha)

##########################################################################################

        def Gower_Similarity_Python(i,j, Mixed_Data_Set, p1, p2, p3):

            X = Mixed_Data_Set

   # The data matrix X have to be order in the following way:
   # The p1 first are quantitative, the following p2 are binary categorical, and the following p3 are multiple categorical.

   #####################################################################################
        
            def G(k, X):

                range = X[:,k].max() - X[:,k].min() 

                return(range)

            G_vector = np.repeat(0, p1)

            for r in range(0, p1):

                G_vector[r] = G(r, X)
                
      
    ##########################################################################################
    
            ones = np.repeat(1, p1)

            Quantitative_Data = X[: , 0:p1]

            Binary_Data = X[: , (p1):(p1+p2)]
            
            Multiple_Categorical_Data = X[: , (p1+p2):(p1+p2+p3) ]

    ##########################################################################################

            numerator_part_1 = ( ones - ( abs(Quantitative_Data[i-1,:] - Quantitative_Data[j-1,:]) / G_vector ) ).sum() 

            numerator_part_2 = a(Binary_Data)[i-1,j-1] + alpha_py_Parallel(i,j, Multiple_Categorical_Data)

            numerator = numerator_part_1 + numerator_part_2
 
            denominator = p1 + (p2 - d(Binary_Data)[i-1,j-1]) + p3

            Similarity_Gower = numerator / denominator  

            return(Similarity_Gower)
  
##########################################################################################

        def Dist_Gower_Py(i, j, Mixed_Data , p1, p2, p3):

            Dist_Gower = np.sqrt( 1 - Gower_Similarity_Python(i, j, Mixed_Data , p1, p2, p3) )

            return(Dist_Gower)    

    ###################################################################

    ## PARTE DEL CODIGO A PARALELIZAR

        # for i in range(1, len(X)):

            # distances.append( Dist_Gower_Py( len(X), i , X, p1, p2, p3) )

        n_jobs  = multiprocessing.cpu_count()

        distances = Parallel(n_jobs=n_jobs)( delayed(Dist_Gower_Py)( len(X), i , X, p1, p2, p3) for i in range(1, len(X)) )

######################################################################################################################################
 

                                     
    return distances   

In [17]:
distances = KNN_regression_Parallel_Numpy( X_train.iloc[0:100] , Y_train.iloc[0:100], x_new, k=10, distance = "Gower" , p1=5, p2=2, p3=1  )

In [18]:
distances

[array([0.82743439]),
 array([0.7587987]),
 array([0.74934525]),
 array([0.80010854]),
 array([0.82990269]),
 array([0.77710832]),
 array([0.73744569]),
 array([0.80474589]),
 array([0.77639558]),
 array([0.79330666]),
 array([0.7695813]),
 array([0.7959259]),
 array([0.71588872]),
 array([0.78737624]),
 array([0.83205628]),
 array([0.77292423]),
 array([0.76936995]),
 array([0.72059922]),
 array([0.77070144]),
 array([0.79453382]),
 array([0.7740156]),
 array([0.75245411]),
 array([0.77036314]),
 array([0.78407589]),
 array([0.85793336]),
 array([0.77660934]),
 array([0.77458827]),
 array([0.76291423]),
 array([0.71888693]),
 array([0.79945116]),
 array([0.71352599]),
 array([0.89778029]),
 array([0.77473514]),
 array([0.73405666]),
 array([0.7323361]),
 array([0.78552762]),
 array([0.74014494]),
 array([0.71363814]),
 array([0.71298428]),
 array([0.73393082]),
 array([0.74579166]),
 array([0.73683502]),
 array([0.77727169]),
 array([0.77283902]),
 array([0.7136991]),
 array([0.774881

In [ ]:
    distances = pd.DataFrame({'distances': distances})

    distances = distances.sort_values(by=["distances"]).reset_index(drop=False)
        
    knn = distances.iloc[0:k , :]

    for i in knn.iloc[:,0]:

        Y_values_knn.append(Y[i, ])

In [179]:
x_new = Data_Houses_Prices_Test.iloc[ 1 , range(1, Data_Houses_Prices_Test.shape[1])]

In [15]:
KNN_regression_Parallel_Numpy( X_train.iloc[0:100] , Y_train.iloc[0:100], x_new, k=10, distance = "Gower" , p1=5, p2=2, p3=1  )

1618866.0

In [181]:
def validacion_simple_Parallel_Numpy(Data_Test, X_train, Y_train):

    ##########################

    from joblib import Parallel, delayed
    import multiprocessing

    n_jobs  = multiprocessing.cpu_count()

    ##########################

    def prediction(i, Data_Test, X_train, Y_train ):

     x_new = Data_Test.iloc[ i , range(1,Data_Test.shape[1])]

     # Usamos KNN_regression_Parallel en vez de KNN_regression
 
     y_new_predict = KNN_regression_Parallel_Numpy( X_train  , Y_train , x_new, k=10, distance = "Gower" , p1=5, p2=2, p3=1  )

     return(y_new_predict)

    ##########################

    y_predictions_vector = []

    # Paralelizamos el siguiente bucle for :

    # for i in  range(0, len(Data_Test)):

        # y_new_predict = prediction(i, Data_Test, X_train, Y_train )

        # y_predictions_vector.append( y_new_predict )

    
    y_predictions_vector = Parallel(n_jobs=n_jobs)( delayed(prediction)( i, Data_Test, X_train, Y_train) for i in range(0, len(Data_Test)) )

    #########################

    ECM = ( (y_predictions_vector - Data_Test.loc[: , 'Y'])**2 ).sum() 


    return(y_predictions_vector, ECM)

In [183]:
y_predictions_vector, ECM = validacion_simple_Parallel_Numpy(Data_Houses_Prices_Test, X_train.iloc[0:100] , Y_train.iloc[0:100])

In [184]:
ECM

2709375912557313.0

https://www.cienciadedatos.net/documentos/py12-paralelizar-con-python.html