## KNN for supervised classification   

We have $\hspace{0.1cm} p \hspace{0.1cm}$ variables $\hspace{0.1cm} X=(X_1,...,X_p) \hspace{0.1cm}$ measurements on a $n$ size sample.

Also we have a categorical variable $\hspace{0.1cm} Y \hspace{0.1cm}$ with $\hspace{0.1cm} g \hspace{0.1cm}$  categories that indicates  the group to which each element of the sample belongs  $ ( \hspace{0.05cm} Range(Y)=\lbrace c_1 ,..., c_g \rbrace \hspace{0.05cm})$

The groups generated by $\hspace{0.1cm} Y \hspace{0.1cm}$ are denoted as $\hspace{0.1cm} \Omega_1 ,..., \Omega_g \hspace{0.15cm}$   $\hspace{0.15cm}( \hspace{0.1cm} y_i = c_r \hspace{0.15cm} \Leftrightarrow \hspace{0.15cm}$  $ i \in \Omega_r \hspace{0.1cm})$



The supervised classification problem consists in, for a new observation $\hspace{0.1cm} x_{new} = (x_{new,1},x_{new,2},...,x_{new,p}) \hspace{0.1cm}$ of the variables $X_1,...,X_p  \hspace{0.1cm}$, predict its $\hspace{0.1cm} Y \hspace{0.1cm}$ value $\hspace{0.1cm} (y_{new})\hspace{0.1cm}$  using the information of $\hspace{0.1cm} X_1,...,X_p \hspace{0.1cm}$ and $ \hspace{0.1cm} Y$

So , the problem is to classify a new element/individual in one of the $\hspace{0.1cm} g \hspace{0.1cm}$ groups generated by $\hspace{0.1cm} Y \hspace{0.1cm}$ using the information available of $\hspace{0.1cm} X_1,...,X_p \hspace{0.1cm}$ and $Y$, and also $\hspace{0.1cm} x_{new} = (x_{new,1},x_{new,2},...,x_{new,p})$

The KNN (K-nearest neighbors) algorithm have the following steps:

 $1. \hspace{0.15cm}$ Define a distance measure between the observation of the original sample respect to the variables $X_1,...,X_p$ $\hspace{0.15cm} \Rightarrow \hspace{0.15cm}$ $\delta$



 $2. \hspace{0.15cm}$ Compute the distances between $x_{new}$ and the initial observations $\hspace{0.1cm} \lbrace x_1,...,x_n \rbrace$ $\hspace{0.15cm} \Rightarrow \hspace{0.15cm}$ $\lbrace \hspace{0.1 cm}  \delta(x_{new}, x_i) \hspace{0.1 cm} / \hspace{0.1 cm}  i=1,...,n \hspace{0.1 cm}  \rbrace$

  
 $3. \hspace{0.15cm}$ Select the  $k$ nearest observation to $x_{new}$ based on $\hspace{0.05cm} \delta \hspace{0.12cm}$ $(k$ nearest neighbors of $x_{new})$ $\hspace{0.15cm} \Rightarrow \hspace{0.15cm}$   The set of these observation will be denote by $KNN$ 

 $4. \hspace{0.15cm}$ Compute the proportion of these observation (neighbors) that belongs to each group $\hspace{0.15cm} \Rightarrow \hspace{0.15cm}$  
 
 $\hspace{0.65cm} \Rightarrow \hspace{0.15cm}$ The proportion of $KNN$ that belongs to the group $\hspace{0.15cm} \Omega_r$ $\hspace{0.1cm}(Y=c_r)\hspace{0.1cm}$ will be denote by $\hspace{0.1 cm} f^{knn}_{r}  $



   $$ \hspace{0.1 cm} f^{knn}_{r} \hspace{0.15cm}=\hspace{0.15cm} \dfrac{ \# \hspace{0.1cm}\lbrace\hspace{0.1cm} i \in KNN \hspace{0.1cm}/\hspace{0.1cm} i \in \Omega_r \hspace{0.1cm}\rbrace  }{k} $$
   


$5. \hspace{0.15cm}$ Classify $\hspace{0.1cm} x_{new} \hspace{0.1cm}$ in that group such has a bigger neighbors proportion $\hspace{0.18cm} \Rightarrow \hspace{0.18cm}$ If $\hspace{0.1cm} f^{knn}_{s} \geqslant f^{knn}_{r} \hspace{0.1cm}$   $\hspace{0.1cm} \forall r = 1,...,g \hspace{0.1cm}  \Rightarrow \hspace{0.1cm} x_{new} \hspace{0.1cm}$ is classify in $\hspace{0.1cm} \Omega_s$

### Toy example:

Sample: $n=3$

Predictors:

$X1 = (10 , 2 , 4)$
$X2 = (20 , 25, 40)$

Observations:

$x_1 =(10,20)$
$x_2=(2,25)$
$x_3=(4,40)$

Response: (2 categories (0,1), then 2 groups $\Omega_0 , \Omega_1$)

$Y =( 1 , 1 , 0 )$

Distance $\hspace{0.15cm} \Rightarrow \hspace{0.15cm}$  $ \delta_{Euclidean}$

New observation:

$x_{new}=(6, 20)$

Computing the distances:

$\delta(x_{new}, x_1)_{Euclidean} = (10-6)^2 + (20-20)^2 = 16$
$\delta(x_{new}, x_2)_{Euclidean} = (2-6)^2 + (25-20)^2 = 16 + 25 = 41$
$\delta(x_{new}, x_3)_{Euclidean} = (4-6)^2 + (40-20)^2 = 4 + 400 = 404$

Selecting k=2 nearest neighbor to $x_{new}$: $x_1$ and $x_2$

Computing the proportions $f^{knn}$ : $f^{knn}_0 =  0/2 = 0$ , $f^{knn}_1 =  2/2 = 1$

So, the algorithm classify $x_{new}$ in the group $\Omega_1$ , so the algorithm predict that $y_{new} = 1$


Why KNN is a supervised classification method and not an unsupervised ?

Because in this problem we have a vector of observations of the response variable $Y$

The fact that we haven't $\hspace{0.1 cm} y_{new} \hspace{0.1 cm}$ doesn't transform it in a unsupervised problem

Optimal k (ver Aurea)

The typical approach to select the value of $k$ is to set $k=\sqrt{n}$

A more complex approach is the following:


Tenemos x_i=(x_{i1},...,x_{ip}) y tambien y_i para i =1,...,n

Suponer que x_i es una observacion no clasificada (auqnue realmente conocemos y_i) 

Fijar un valor de k

Clasificar x_i usando KNN

Determinar si la clasificacion ha sido correcta o incorrecta (lo podemos hacer gracias a que tenemos el dato y_i)

Repetir el proceso para el resto de i=1,....,n 

Calcular la proporcion de clasificaciones correctas (proporcion de aciertos)  , esta sera la metrica de error del KNN para el hiperparametro k

Repetir el proceso para el resto de k=2,3,...

Seleccionar el valor de k que maximiza la proporcion de aciertos (minimiza la proporcion de errores)

KNN in Python

In [8]:
import pandas as pd

In [190]:
Gender_classification = pd.read_csv('gender_classification.csv')

In [191]:
Gender_classification

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [5]:
import sklearn

from sklearn.neighbors import NearestNeighbors

In [35]:
knn = sklearn.neighbors.KNeighborsClassifier(n_neighbors=10 ,  weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)

n_neighbors = Number of neighbors to use (k)
weights:
   ‘uniform’ : uniform weights. All points in each neighborhood are weighted equally.

   ‘distance’ : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.

   [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.

metric:

  Metric to use for distance computation. Default is “minkowski”, which results in the standard Euclidean distance when p = 2. See the documentation of scipy.spatial.distance and the metrics listed in distance_metrics for valid metric values.

  If metric is “precomputed”, X is assumed to be a distance matrix and must be square during fit.



In [170]:
X = Gender_classification.iloc[0:20 , 0:7]

In [187]:
 Y = Gender_classification.iloc[0:20 , 7]

In [48]:
knn.fit(X, Y)

KNeighborsClassifier(n_neighbors=10)

In [49]:
x_new = [1,	10, 5, 1, 0, 1,	1]

In [50]:
print( knn.predict( [x_new] ) ) 

['Female']


c:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [51]:
print( knn.predict_proba([x_new]) )

[[0.6 0.4]]


c:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [43]:
import numpy as np

In [131]:
def Dist_Euclidea_Python(i, j, Quantitative_Data_set):

    Dist_Euclidea = ( ( Quantitative_Data_set.iloc[i-1, ] - Quantitative_Data_set.iloc[j-1, ] )**2 ).sum()

    Dist_Euclidea = np.sqrt(Dist_Euclidea)

    return Dist_Euclidea

In [41]:
def Dist_Euclidea_Matrix_Python( Quantitative_Data_set ):

    M = np.zeros((Quantitative_Data_set.shape[0] , Quantitative_Data_set.shape[0]))

    for i in range(0 , Quantitative_Data_set.shape[0]):
        for j in range(0 , Quantitative_Data_set.shape[0]):

            M[i,j]=Dist_Euclidea_Python(i+1,j+1, Quantitative_Data_set)
                 
    return M

In [ ]:

def KNN_Fabio_Scielzo_Ortiz( X , Y , x_new, k distance = "euclidean"):

    X = pd.concat([X, x_new.to_frame().T], ignore_index=True)

    if distance == "euclidean":

        def Dist_Euclidea_Python(i, j, Quantitative_Data_set): 

            Dist_Euclidea = ( ( Quantitative_Data_set.iloc[i-1, ] - Quantitative_Data_set.iloc[j-1, ] )**2 ).sum()

            Dist_Euclidea = np.sqrt(Dist_Euclidea)

            return Dist_Euclidea

    Dist_Euclidea_Python(len(X), i , X)
         

        

In [172]:
X = pd.concat([X, x_new.to_frame().T], ignore_index=True)
X

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0           1               11.8                 6.1          1          0   
1           0               14.0                 5.4          0          0   
2           0               11.8                 6.3          1          1   
3           0               14.4                 6.1          0          1   
4           1               13.5                 5.9          0          0   
5           1               13.0                 6.8          1          1   
6           1               15.3                 6.2          1          1   
7           0               13.0                 5.2          0          0   
8           1               11.9                 5.4          1          0   
9           1               12.1                 5.4          0          0   
10          0               12.5                 5.4          1          1   
11          1               15.5                 5.8          1          1   
12          0               14.7                 5.2          1          1   
13          1               14.5                 6.7          0          1   
14          1               14.2                 6.5          0          0   
15          0               12.5                 5.2          1          1   
16          1               15.2                 6.0          1          1   
17          1               14.0                 5.9          0          0   
18          1               11.9                 5.2          0          0   
19          1               14.4                 5.6          1          0   
20          1                4.0                 6.0          1          1   

    lips_thin  distance_nose_to_lip_long  
0           1                          1  
1           1                          0  
2           1                          1  
3           1                          1  
4           0                          0  
5           1                          1  
6           1                          0  
7           0                          0  
8           1                          1  
9           0                          0  
10          1                          1  
11          1                          1  
12          1                          1  
13          1                          1  
14          0                          0  
15          1                          1  
16          1                          1  
17          0                          0  
18          0                          0  
19          1                          1  
20          1                          1

In [173]:
distances = []


In [174]:
for i in range(1, len(X)):

    distances.append( Dist_Euclidea_Python( len(X), i , X) )


In [175]:
distances

[7.864477096412704,
 10.215674231297706,
 7.86956161421969,
 10.496189784869555,
 9.708758932015977,
 9.035485598461214,
 11.345924378383632,
 9.308061022576076,
 7.985612061701971,
 8.364807230295268,
 8.579627031520658,
 11.501738998951419,
 10.776363022838456,
 10.570714261581381,
 10.406248123122953,
 8.595929269136642,
 11.2,
 10.198529305738157,
 8.18840643837371,
 10.455620498086185]

In [176]:

distances = pd.DataFrame({'distances': distances})


In [177]:

distances = distances.sort_values(by=["distances"]).reset_index(drop=False)


In [178]:
distances

index  distances
0       0   7.864477
1       2   7.869562
2       8   7.985612
3      18   8.188406
4       9   8.364807
5      10   8.579627
6      15   8.595929
7       5   9.035486
8       7   9.308061
9       4   9.708759
10     17  10.198529
11      1  10.215674
12     14  10.406248
13     19  10.455620
14      3  10.496190
15     13  10.570714
16     12  10.776363
17     16  11.200000
18      6  11.345924
19     11  11.501739

In [179]:
k=5
knn = distances.iloc[0:k , :]

In [180]:
knn

index  distances
0      0   7.864477
1      2   7.869562
2      8   7.985612
3     18   8.188406
4      9   8.364807

In [200]:
for i in range(0, len(Y)):

    if Y[i]=='Male':

        Y[i] = 0

    elif Y[i]=='Female':

        Y[i]=1


In [219]:
groups_knn = []


In [220]:

for i in knn.iloc[:,0]:

    groups_knn.append(Y[i])


In [221]:
groups_knn

[0, 0, 1, 1, 1]

In [245]:
unique, counts = np.unique(groups_knn , return_counts=True)


In [224]:
counts

array([2, 3], dtype=int64)

In [232]:
unique

array([0, 1])

In [227]:
dict(zip(unique, counts))

{0: 2, 1: 3}

In [226]:
counts/k

array([0.4, 0.6])

In [242]:
unique_Y , counts_Y = np.unique(Y , return_counts=True)

In [243]:
unique_Y

array([0, 1], dtype=object)

In [247]:
proportions_groups_knn = pd.DataFrame({'proportions_groups': counts/k, 'groups': unique_Y })

In [248]:
proportions_groups_knn

proportions_groups groups
0                 0.4      0
1                 0.6      1

In [250]:
proportions_groups_knn.max()['groups'] # X_new is classify as Y=1 (female)

1

In [127]:
x_new = pd.Series({'long_hair': 1, 'forehead_width_cm': 4, 'forehead_height_cm': 6, 'nose_wide': 1 , 'nose_long': 1 , 'nose_long': 1 , 'lips_thin':1, 'distance_nose_to_lip_long': 1 })

In [128]:
pd.concat([X, x_new.to_frame().T], ignore_index=True)

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0           0               14.0                 5.4          0          0   
1           0               11.8                 6.3          1          1   
2           0               14.4                 6.1          0          1   
3           1               13.5                 5.9          0          0   
4           1               13.0                 6.8          1          1   
5           1               15.3                 6.2          1          1   
6           0               13.0                 5.2          0          0   
7           1               11.9                 5.4          1          0   
8           1               12.1                 5.4          0          0   
9           0               12.5                 5.4          1          1   
10          1               15.5                 5.8          1          1   
11          0               14.7                 5.2          1          1   
12          1               14.5                 6.7          0          1   
13          1               14.2                 6.5          0          0   
14          0               12.5                 5.2          1          1   
15          1               15.2                 6.0          1          1   
16          1               14.0                 5.9          0          0   
17          1               11.9                 5.2          0          0   
18          1               14.4                 5.6          1          0   
19          1                4.0                 6.0          1          1   

    lips_thin  distance_nose_to_lip_long  
0           1                          0  
1           1                          1  
2           1                          1  
3           0                          0  
4           1                          1  
5           1                          0  
6           0                          0  
7           1                          1  
8           0                          0  
9           1                          1  
10          1                          1  
11          1                          1  
12          1                          1  
13          0                          0  
14          1                          1  
15          1                          1  
16          0                          0  
17          0                          0  
18          1                          1  
19          1                          1

KNN para regresion