# Data Manipulation in Python with `Pandas`

This article is about data manipulation in Python using `Pandas`, one of the most important Python packages.


## Indice:
* [Load Packages](#1)
* [Vectors in Python](#2)
* [Data-frames in Python](#3)
* * [Load a Data-frame](#4)
* * [Export a data-frame in csv format](#5)
* * [Numeric Summary](#6)
* * [Create a Data-frame manually](#7)
* * [Data-frame dimensions](#8)
* * [Transpose a data-frame](#9)
* * [Add new variables to a data-frame](#10)
* * [Selecting rows and columns in a data-frame](#11)
* * [Filtering observations (rows) in a data-frame](#12)
* * [Deleting columns in a data-frame](#13)
* * [Working with NaN in a data-frame](#14)
* * [Grouping and summarizing in a data-frame](#15)
* * [Join data-frames](#16)
* * [Rename columns](#17)
* * [Rename rows](#18)
*  [Numeric Sequencies](#19)
*  [Functions and loops](#20)
*  [Brief summary of matrix with Numpy](#21)



## Load Packages <a class="anchor" id="1"></a>

We load the Python packages that we are going to use:

In [2]:
import pandas as pd
import numpy as np
import array as arr

from IPython.display import display
pd.options.display.max_columns = None

In [3]:
import warnings
warnings.filterwarnings('ignore')

## Vectors in Python <a class="anchor" id="2"></a>

In Python the objects most liked to R vectors are `series`, that is an element of `Pandas` package.




In [4]:
vector = pd.Series([0.25, 0.5, 0.75, 1.0])
vector

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
elements=[0.25, 0.5, 0.75, 1.0]
vector = pd.Series(elements)
vector

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The *series* element has two atributes, `data.values` and `data.index` . 

`data.values` are the data of the vector.
`data.index` are the names of the vector elements.

In [1]:
vector_1 = pd.Series(data = [46350000, 44380000, 18120000, 31970000, 10330000], 
                     index=['Spain', 'Argentina', 'Chile', 'Peru', 'Cuba'])
vector_1

NameError: name 'pd' is not defined

Another way to create a vector in Python:

In [7]:
vector_2 = {'Spain': 46350000, 'Argentina': 44380000, 
            'Chile': 18120000, 'Peru': 31970000, 'Cuba': 10330000}

vector_2 = pd.Series(vector_2)

vector_2

Spain        46350000
Argentina    44380000
Chile        18120000
Peru         31970000
Cuba         10330000
dtype: int64

We can select the elements of a vector (`series`) as follows:

**Warning:** the natural index in Python is 0,1,2,... , so it begins in zero (0) , we have to be careful with that.

In [8]:
vector_1[0]

46350000

In [9]:
vector_1[1]

44380000

In [10]:
vector_1[0:3]

Spain        46350000
Argentina    44380000
Chile        18120000
dtype: int64

In [11]:
vector_1["Spain":"Chile"]

Spain        46350000
Argentina    44380000
Chile        18120000
dtype: int64

## Data-frames in Python <a class="anchor" id="3"></a>

A data-frame is a set of `series` that has two index, one associated to the rows and other to the columns.


### Load a Data-frame <a class="anchor" id="4"></a>
We load the data-set:


The url where the data-set is hosted is:

https://raw.githubusercontent.com/FabioScielzoOrtiz/Estadistica4all-blog/main/Data%20Manipulation%20in%20Python/properties_data.csv


In [12]:
url = 'https://raw.githubusercontent.com/FabioScielzoOrtiz/Estadistica4all-blog/main/Data%20Manipulation%20in%20Python/properties_data.csv'
data = pd.read_csv(url)
data

id                       neighborhood   latitude  longitude  \
0     5528049                      Palm Jumeirah  25.000000  55.138932   
1     6008529                      Palm Jumeirah  25.106809  55.151201   
2     6034542               Jumeirah Lake Towers  25.063302  55.137728   
3     6326063                    Culture Village  25.227295  55.341761   
4     6356778                      Palm Jumeirah  25.114275  55.139764   
...       ...                                ...        ...        ...   
1900  7705450           Mohammed Bin Rashid City  25.176892  55.310712   
1901  7706287           Mohammed Bin Rashid City  25.166145  55.276684   
1902  7706389  Dubai Creek Harbour (The Lagoons)  25.206500  55.345056   
1903  7706591            Jumeirah Village Circle  25.073858  55.229844   
1904  7706643               Jumeirah Lake Towers  25.079130  55.154713   

        price  size_in_sqft  price_per_sqft  no_of_bedrooms  no_of_bathrooms  \
0     2700000          1079         2502.32               1                2   
1     2850000          1582         1801.52               2                2   
2     1150000          1951          589.44               3                5   
3     2850000          2020         1410.89               2                3   
4     1729200           507         3410.65               0                1   
...       ...           ...             ...             ...              ...   
1900  1500000          1087         1379.94               2                2   
1901  1230000           760         1618.42               1                2   
1902  2900000          1930         1502.59               3                5   
1903   675000           740          912.16               1                2   
1904   760887           800          951.11               1                2   

     quality  maid_room  unfurnished  balcony  barbecue_area  \
0     Medium      False        False     True           True   
1     Medium      False        False     True          False   
2     Medium       True         True     True          False   
3        Low      False         True     True          False   
4     Medium      False        False    False          False   
...      ...        ...          ...      ...            ...   
1900   Ultra      False         True     True           True   
1901  Medium      False        False     True          False   
1902  Medium       True         True     True          False   
1903  Medium      False         True     True          False   
1904    High      False        False     True           True   

      built_in_wardrobes  central_ac  childrens_play_area  childrens_pool  \
0                  False        True                 True           False   
1                   True        True                 True           False   
2                   True       False                False           False   
3                  False       False                False           False   
4                   True        True                False           False   
...                  ...         ...                  ...             ...   
1900                True        True                 True            True   
1901                True        True                 True           False   
1902               False        True                 True           False   
1903                True        True                 True           False   
1904                True        True                 True            True   

      concierge  covered_parking  kitchen_appliances  lobby_in_building  \
0          True            False                True              False   
1         False            False               False              False   
2         False             True               False              False   
3          True             True               False              False   
4         False             True                True              False   
...         ...  

### Export a Data-frame in csv format <a class="anchor" id="5"></a>

In [13]:
# We have the following data frame: df

# df.to_csv('filename.csv', index=False)  
 
## We create the file 'filename.csv' with the data frame 'df'

### Number of rows and columns of a data-frame <a class="anchor" id="6"></a>

We can compute the number of rows and columns of the data set as following:

In [14]:
ncol=len(data.columns)
nrow=len(data)

In [15]:
ncol 


38

In [16]:
nrow

1905

### Numeric Summary <a class="anchor" id="6"></a>
We can compute a numeric summary of the data-set variables:

In [17]:
data.describe()

id     latitude    longitude         price  size_in_sqft  \
count  1.905000e+03  1905.000000  1905.000000  1.905000e+03   1905.000000   
mean   7.573308e+06    25.116479    55.212338  2.085830e+06   1417.050394   
std    1.925252e+05     0.062704     0.068794  2.913200e+06    891.487639   
min    5.528049e+06    24.865992    55.069311  2.200000e+05    294.000000   
25%    7.560167e+06    25.072697    55.145389  8.900000e+05    840.000000   
50%    7.631829e+06    25.096545    55.207506  1.400000e+06   1271.000000   
75%    7.670328e+06    25.188130    55.271797  2.200000e+06   1703.000000   
max    7.706643e+06    25.273623    55.441623  3.500000e+07   9576.000000   

       price_per_sqft  no_of_bedrooms  no_of_bathrooms  
count     1905.000000     1905.000000      1905.000000  
mean      1327.243785        1.793176         2.512861  
std        668.473559        0.949489         1.063117  
min        361.870000        0.000000         1.000000  
25%        870.920000        1.000000         2.000000  
50%       1169.590000        2.000000         2.000000  
75%       1622.500000        2.000000         3.000000  
max       4805.870000        5.000000         6.000000

### Create a Data-frame manually <a class="anchor" id="7"></a>


We can create a data-frame manually as follows.

First we create the variables of the data-frame:

In [18]:
variable_1 = pd.Series({'Spain': 46350000, 'Argentina': 44380000, 
                        'Chile': 18120000, 'Peru': 31970000, 'Cuba': 10330000})
variable_1

Spain        46350000
Argentina    44380000
Chile        18120000
Peru         31970000
Cuba         10330000
dtype: int64

In [19]:
variable_2 = pd.Series({'Spain': 5, 'Argentina': 6, 'Chile': 3, 
                         'Peru': 2, 'Cuba': 1.5})
variable_2

Spain        5.0
Argentina    6.0
Chile        3.0
Peru         2.0
Cuba         1.5
dtype: float64

Now we create the data-frame using the above variables:

In [20]:
data_frame = pd.DataFrame({'variable 1': variable_1, 
                           'variable 2': variable_2})
data_frame

variable 1  variable 2
Spain        46350000         5.0
Argentina    44380000         6.0
Chile        18120000         3.0
Peru         31970000         2.0
Cuba         10330000         1.5

Another way to create a data-frame in Python:

In [21]:
data_frame = pd.DataFrame(
    {'variable 1': [46350000, 44380000, 18120000, 31970000, 10330000], 
     'variable 2': [5, 6, 3, 2, 1.5] } , 
    index=['Spain','Argentina', 'Chile', 'Peru', 'Cuba'])
    
data_frame

variable 1  variable 2
Spain        46350000         5.0
Argentina    44380000         6.0
Chile        18120000         3.0
Peru         31970000         2.0
Cuba         10330000         1.5

In [22]:
df  = pd.DataFrame({'X1':[ 55 , np.nan , 85, np.nan, 63 ] , 
                    'X2': [10, 12, np.nan, 30, -13] , 
                    'X3': [ 22 , 7, 40, 16, 45 ] } ,
                index=['Spain','Argentina', 'Chile', 'Peru', 'Cuba']  )

df

X1    X2  X3
Spain      55.0  10.0  22
Argentina   NaN  12.0   7
Chile      85.0   NaN  40
Peru        NaN  30.0  16
Cuba       63.0 -13.0  45

And another way to create data-frames manually:

In [23]:
X1 = pd.Series([ 55 , np.nan , 85, np.nan, 63 ])
X2 = pd.Series([10, 12, np.nan, 30, -13])
X3 = pd.Series([ 22 , 7, 40, 16, 45 ])
X4 = pd.Series([15, 22, 5, -30, np.nan])

df  = pd.DataFrame( {"X1": X1 , "X2": X2 , "X3": X3 , "X4": X4} )
df

X1    X2  X3    X4
0  55.0  10.0  22  15.0
1   NaN  12.0   7  22.0
2  85.0   NaN  40   5.0
3   NaN  30.0  16 -30.0
4  63.0 -13.0  45   NaN

Using this way you cannot set an index like before.

###  Data-frame dimensions <a class="anchor" id="8"></a>

We can get the dimensions of the data-frame:

In [24]:
data_frame.values.shape

(5, 2)

###  Transpose a data-frame <a class="anchor" id="9"></a>

We can transpose the data-frame:

In [25]:
data_frame.T

Spain   Argentina       Chile        Peru        Cuba
variable 1  46350000.0  44380000.0  18120000.0  31970000.0  10330000.0
variable 2         5.0         6.0         3.0         2.0         1.5

###  Adding new variables to a data-frame <a class="anchor" id="10"></a>

We can add new variables to the data-frame as follows:

In [26]:
data_frame['variable 3'] = ['Europe', 'South America', 'South America', 
                            'South America', 'Caribbean']
                            
data_frame

variable 1  variable 2     variable 3
Spain        46350000         5.0         Europe
Argentina    44380000         6.0  South America
Chile        18120000         3.0  South America
Peru         31970000         2.0  South America
Cuba         10330000         1.5      Caribbean

In [27]:
new_variable = round(data_frame['variable 1']/data_frame['variable 2'])

data_frame['new_variable'] = new_variable

data_frame

variable 1  variable 2     variable 3  new_variable
Spain        46350000         5.0         Europe     9270000.0
Argentina    44380000         6.0  South America     7396667.0
Chile        18120000         3.0  South America     6040000.0
Peru         31970000         2.0  South America    15985000.0
Cuba         10330000         1.5      Caribbean     6886667.0

### Selecting rows and columns in a data-frame <a class="anchor" id="11"></a>

We can select rows and columns using `loc` and `iloc` , the first with an explicit index and the second with an implicit index.

In [28]:
data_frame.loc[['Spain']]

variable 1  variable 2 variable 3  new_variable
Spain    46350000         5.0     Europe     9270000.0

In [29]:
data_frame.loc[['Spain', 'Cuba']]

variable 1  variable 2 variable 3  new_variable
Spain    46350000         5.0     Europe     9270000.0
Cuba     10330000         1.5  Caribbean     6886667.0

In [30]:
data_frame.loc[['Spain', 'Cuba','Chile'] , ['variable 2'] ]

variable 2
Spain         5.0
Cuba          1.5
Chile         3.0

In [31]:
data_frame.loc[ ['Spain', 'Cuba','Chile'] , ['variable 2' , 'variable 1'] ]

variable 2  variable 1
Spain         5.0    46350000
Cuba          1.5    10330000
Chile         3.0    18120000

In [32]:
data_frame.iloc[[2] , [0,1,3] ] 

variable 1  variable 2  new_variable
Chile    18120000         3.0     6040000.0

In [33]:
data_frame.iloc[[0, 2, 4] , [1 , 0]]

variable 2  variable 1
Spain         5.0    46350000
Chile         3.0    18120000
Cuba          1.5    10330000

###  Filtering observations (rows) in a data-frame <a class="anchor" id="12"></a>

We can filter observations as well:

In [34]:
data_frame['variable 2']>3

Spain         True
Argentina     True
Chile        False
Peru         False
Cuba         False
Name: variable 2, dtype: bool

In [35]:
data_frame.loc[data_frame['variable 2']>3 , : ]

variable 1  variable 2     variable 3  new_variable
Spain        46350000         5.0         Europe     9270000.0
Argentina    44380000         6.0  South America     7396667.0

Other form of filtering rows:

In [36]:
X1 = pd.Series([ "France" , "Spain" , "Italy", "Russia", "Portugal" ])
X2 = pd.Series([10, 12, 50, 30, -13])
X3 = pd.Series([ 22 , 7, 40, 16, 45 ])
X4 = pd.Series([15, 22, 5, -30, 21])

df  = pd.DataFrame( {"Countries": X1 , "X2": X2 , "X3": X3 , "X4": X4} )

df

Countries  X2  X3  X4
0    France  10  22  15
1     Spain  12   7  22
2     Italy  50  40   5
3    Russia  30  16 -30
4  Portugal -13  45  21

In [37]:
df[df.Countries=="Spain"]

Countries  X2  X3  X4
1     Spain  12   7  22

In [38]:
df[ (df.X2 > 15) & (df.X4 < 20) ]

Countries  X2  X3  X4
2     Italy  50  40   5
3    Russia  30  16 -30

In [39]:
df[ (df.X2 > 15) | (df.X4 < 20) ]

Countries  X2  X3  X4
0    France  10  22  15
2     Italy  50  40   5
3    Russia  30  16 -30

In [40]:
X1 = pd.Series([ "France" , "Spain" , "Italy", "Russia", "USA" ])
X2 = pd.Series([ "Europe" , "Europe" , "Europe", "Not Europe", "Not Europe" ])
X3 = pd.Series([10, 12, 50, 30, -13])
X4 = pd.Series([ 22 , 7, 40, 16, 45 ])
X5 = pd.Series([15, 22, 5, -30, 21])

df  = pd.DataFrame( {"Countries": X1 , "Continent": X2 , "X3": X3 , 
                    "X4": X4 ,"X5": X5} )
df

Countries   Continent  X3  X4  X5
0    France      Europe  10  22  15
1     Spain      Europe  12   7  22
2     Italy      Europe  50  40   5
3    Russia  Not Europe  30  16 -30
4       USA  Not Europe -13  45  21

In [41]:
df[ (df.Continent == "Europe") & (df.X4 < 25) ]

Countries Continent  X3  X4  X5
0    France    Europe  10  22  15
1     Spain    Europe  12   7  22

###  Deleting columns in a data-frame <a class="anchor" id="13"></a>

Delete columns:

In [42]:
del [ df['X3'] ]

df

Countries   Continent  X4  X5
0    France      Europe  22  15
1     Spain      Europe   7  22
2     Italy      Europe  40   5
3    Russia  Not Europe  16 -30
4       USA  Not Europe  45  21

### Working with NaN in a data-frame  <a class="anchor" id="14"></a>

We are going to create several data-frames with NaN´s, and later we are going to deal with them.

In [43]:
X1 = pd.Series([ 55 , np.nan , 85, np.nan, 63 ])
X2 = pd.Series([10, 12, np.nan, 30, -13])
X3 = pd.Series([ 22 , 7, 40, 16, 45 ])
X4 = pd.Series([15, 22, 5, -30, np.nan])

df_nan  = pd.DataFrame( {"X1": X1 , "X2": X2 , "X3": X3 , "X4": X4} )

df_nan

X1    X2  X3    X4
0  55.0  10.0  22  15.0
1   NaN  12.0   7  22.0
2  85.0   NaN  40   5.0
3   NaN  30.0  16 -30.0
4  63.0 -13.0  45   NaN

In [44]:
 df_nan.isnull()

X1     X2     X3     X4
0  False  False  False  False
1   True  False  False  False
2  False   True  False  False
3   True  False  False  False
4  False  False  False   True

In [45]:
 df_nan.isnull().sum()

X1    2
X2    1
X3    0
X4    1
dtype: int64

In [46]:
df_nan.dropna() # Elimina filas con datos faltantes

X1    X2  X3    X4
0  55.0  10.0  22  15.0

In [47]:
df_nan.dropna(axis=1)  # Elimina columnas con datos faltantes

X3
0  22
1   7
2  40
3  16
4  45

In [48]:
df_nan.dropna(axis=1, how='all') 

X1    X2  X3    X4
0  55.0  10.0  22  15.0
1   NaN  12.0   7  22.0
2  85.0   NaN  40   5.0
3   NaN  30.0  16 -30.0
4  63.0 -13.0  45   NaN

In [49]:
df_nan.dropna(thresh=2)

X1    X2  X3    X4
0  55.0  10.0  22  15.0
1   NaN  12.0   7  22.0
2  85.0   NaN  40   5.0
3   NaN  30.0  16 -30.0
4  63.0 -13.0  45   NaN

In [50]:
df_nan.fillna(0)  # Rellenar con 0

X1    X2  X3    X4
0  55.0  10.0  22  15.0
1   0.0  12.0   7  22.0
2  85.0   0.0  40   5.0
3   0.0  30.0  16 -30.0
4  63.0 -13.0  45   0.0

In [51]:
df_nan.fillna(method='bfill')  # Rellenar con el valor siguiente

X1    X2  X3    X4
0  55.0  10.0  22  15.0
1  85.0  12.0   7  22.0
2  85.0  30.0  40   5.0
3  63.0  30.0  16 -30.0
4  63.0 -13.0  45   NaN

In [52]:
df_nan.fillna(df_nan.mean())  # Rellenar con la media de cada columna

X1     X2  X3    X4
0  55.000000  10.00  22  15.0
1  67.666667  12.00   7  22.0
2  85.000000   9.75  40   5.0
3  67.666667  30.00  16 -30.0
4  63.000000 -13.00  45   3.0

In [53]:
df_nan.fillna(df_nan.median())  # Rellenar con la mediana de cada columna

X1    X2  X3    X4
0  55.0  10.0  22  15.0
1  63.0  12.0   7  22.0
2  85.0  11.0  40   5.0
3  63.0  30.0  16 -30.0
4  63.0 -13.0  45  10.0

###  Grouping and summarizing in a data-frame <a class="anchor" id="15"></a>

Group by and summarize:

In [54]:
X1 = pd.Series([ "Masculino" , "Femenino" , "Masculino", 
                 "Masculino", "Femenino" ])
X2 = pd.Series([10, 12, 32, 30, -13])
X3 = pd.Series([ 22 , 7, 40, 16, 45 ])
X4 = pd.Series([15, 22, 5, -30, 23])

df = pd.DataFrame( {"Sex": X1 , "X2": X2 , "X3": X3 , "X4": X4} ) 
df

Sex  X2  X3  X4
0  Masculino  10  22  15
1   Femenino  12   7  22
2  Masculino  32  40   5
3  Masculino  30  16 -30
4   Femenino -13  45  23

In [55]:
df.groupby('Sex')['X2'].mean()

Sex
Femenino     -0.5
Masculino    24.0
Name: X2, dtype: float64

In [56]:
df.groupby('Sex')['X2'].std()

Sex
Femenino     17.677670
Masculino    12.165525
Name: X2, dtype: float64

In [57]:

df.groupby('Sex')['X2'].min()

Sex
Femenino    -13
Masculino    10
Name: X2, dtype: int64

In [58]:
df.groupby('Sex')['X2'].agg([np.min, np.max, np.median, np.sum, np.std])

amin  amax  median  sum        std
Sex                                          
Femenino    -13    12    -0.5   -1  17.677670
Masculino    10    32    30.0   72  12.165525

###  Join data-frames <a class="anchor" id="16"></a>

In [59]:
X7 = pd.Series([ 22 , 34 , 13, 35, 23 ])
X8 = pd.Series([10, 12, 32, 30, -13])
 

df2 = pd.DataFrame( {"X7": X7 , "X8": X8} ) 
df2

X7  X8
0  22  10
1  34  12
2  13  32
3  35  30
4  23 -13

In [60]:
df

Sex  X2  X3  X4
0  Masculino  10  22  15
1   Femenino  12   7  22
2  Masculino  32  40   5
3  Masculino  30  16 -30
4   Femenino -13  45  23

We can use `concat` to join data-frames as follows:

In [61]:
from pandas import concat

In [62]:
concat([df,df2])

Sex    X2    X3    X4    X7    X8
0  Masculino  10.0  22.0  15.0   NaN   NaN
1   Femenino  12.0   7.0  22.0   NaN   NaN
2  Masculino  32.0  40.0   5.0   NaN   NaN
3  Masculino  30.0  16.0 -30.0   NaN   NaN
4   Femenino -13.0  45.0  23.0   NaN   NaN
0        NaN   NaN   NaN   NaN  22.0  10.0
1        NaN   NaN   NaN   NaN  34.0  12.0
2        NaN   NaN   NaN   NaN  13.0  32.0
3        NaN   NaN   NaN   NaN  35.0  30.0
4        NaN   NaN   NaN   NaN  23.0 -13.0

In [63]:
concat([df,df2] , ignore_index=True)

Sex    X2    X3    X4    X7    X8
0  Masculino  10.0  22.0  15.0   NaN   NaN
1   Femenino  12.0   7.0  22.0   NaN   NaN
2  Masculino  32.0  40.0   5.0   NaN   NaN
3  Masculino  30.0  16.0 -30.0   NaN   NaN
4   Femenino -13.0  45.0  23.0   NaN   NaN
5        NaN   NaN   NaN   NaN  22.0  10.0
6        NaN   NaN   NaN   NaN  34.0  12.0
7        NaN   NaN   NaN   NaN  13.0  32.0
8        NaN   NaN   NaN   NaN  35.0  30.0
9        NaN   NaN   NaN   NaN  23.0 -13.0

The following is equivalent to *cbind* R function

In [64]:
concat([df,df2] , axis=1) # equivalent to cbind R function

Sex  X2  X3  X4  X7  X8
0  Masculino  10  22  15  22  10
1   Femenino  12   7  22  34  12
2  Masculino  32  40   5  13  32
3  Masculino  30  16 -30  35  30
4   Femenino -13  45  23  23 -13

In [65]:
X1 = pd.Series([ 2 , 4 , 3, 35, 23 ])
X2 = pd.Series([10, 12, 3, 3, -13])
X3 = pd.Series([22, 33, 1, 5, -3])
X4 = pd.Series([52, 2, 23, 6, -5])
X5 = pd.Series([ 22 , 34 , 13, 35, 23 ])
X6 = pd.Series([10, 12, 32, 30, -13])
X7 = pd.Series([22, 33, 1, 56, -13])
X8 = pd.Series([5, 12, 2, 66, -5])

df1 = pd.DataFrame( {"X1": X1 , "X2": X2 , "X3": X3 , "X4": X4} ) 

df2 = pd.DataFrame( {"X1": X5 , "X2": X6 , "X3": X7 , "X4": X8} ) 

In [66]:
df1

X1  X2  X3  X4
0   2  10  22  52
1   4  12  33   2
2   3   3   1  23
3  35   3   5   6
4  23 -13  -3  -5

In [67]:
df2

X1  X2  X3  X4
0  22  10  22   5
1  34  12  33  12
2  13  32   1   2
3  35  30  56  66
4  23 -13 -13  -5

The next is equivalent to *rbind* R function:

In [68]:
pd.concat([df1,df2]) # equivalent ti rbind R function

X1  X2  X3  X4
0   2  10  22  52
1   4  12  33   2
2   3   3   1  23
3  35   3   5   6
4  23 -13  -3  -5
0  22  10  22   5
1  34  12  33  12
2  13  32   1   2
3  35  30  56  66
4  23 -13 -13  -5

In [69]:
df_keys = pd.concat([df1,df2], keys=['x', 'y'])
df_keys

X1  X2  X3  X4
x 0   2  10  22  52
  1   4  12  33   2
  2   3   3   1  23
  3  35   3   5   6
  4  23 -13  -3  -5
y 0  22  10  22   5
  1  34  12  33  12
  2  13  32   1   2
  3  35  30  56  66
  4  23 -13 -13  -5

In [70]:
df_keys.loc['x']

X1  X2  X3  X4
0   2  10  22  52
1   4  12  33   2
2   3   3   1  23
3  35   3   5   6
4  23 -13  -3  -5

In [71]:
df_keys.loc['y']

X1  X2  X3  X4
0  22  10  22   5
1  34  12  33  12
2  13  32   1   2
3  35  30  56  66
4  23 -13 -13  -5

Now we are going to show how to use `merge` to join data-frames:

In [72]:
id1 = list(range(1,6)) 
id2 = [1, 3, 6, 7, 2]
X1 = pd.Series([ 2 , 4 , 3, 35, 23 ])
X2 = pd.Series([10, 12, 3, 3, -13])
X3 = pd.Series([22, 33, 1, 5, -3])
X4 = pd.Series([52, 2, 23, 6, -5])
X5 = pd.Series([ 22 , 34 , 13, 35, 23 ])

df1 = pd.DataFrame( {"id": id1 , "X1": X1 , "X2": X2 , "X3": X3 } ) 

df2 = pd.DataFrame( {"id": id2 ,  "X4": X4 , "X5": X5  } ) 

In [73]:
df1

id  X1  X2  X3
0   1   2  10  22
1   2   4  12  33
2   3   3   3   1
3   4  35   3   5
4   5  23 -13  -3

In [74]:
df2

id  X4  X5
0   1  52  22
1   3   2  34
2   6  23  13
3   7   6  35
4   2  -5  23

In [75]:
pd.merge(df1, df2, on='id') # equivalent to an inner join

id  X1  X2  X3  X4  X5
0   1   2  10  22  52  22
1   2   4  12  33  -5  23
2   3   3   3   1   2  34

Now we put different names to the id column of each data-frame:

In [76]:
df1 = pd.DataFrame( {"id1": id1 , "X1": X1 , "X2": X2 , "X3": X3 } ) 

df2 = pd.DataFrame( {"id2": id2 ,  "X4": X4 , "X5": X5  } ) 

In [77]:
# pd.merge(df1, df2, on='id')  ## if we run it, we get an error

The correct way to use `merge` when the names of link columns are different is:

In [78]:
df_merge = pd.merge(df1, df2, left_on='id1' , right_on='id2')
df_merge

id1  X1  X2  X3  id2  X4  X5
0    1   2  10  22    1  52  22
1    2   4  12  33    2  -5  23
2    3   3   3   1    3   2  34

In [79]:
del df_merge['id2']

df_merge

id1  X1  X2  X3  X4  X5
0    1   2  10  22  52  22
1    2   4  12  33  -5  23
2    3   3   3   1   2  34

In [80]:
df1 = pd.DataFrame( {"id": id1 , "X1": X1 , "X2": X2 , "X3": X3 } ) 

df2 = pd.DataFrame( {"id": id2 ,  "X4": X4 , "X5": X5  } ) 

In [81]:
df1

id  X1  X2  X3
0   1   2  10  22
1   2   4  12  33
2   3   3   3   1
3   4  35   3   5
4   5  23 -13  -3

In [82]:
df2

id  X4  X5
0   1  52  22
1   3   2  34
2   6  23  13
3   7   6  35
4   2  -5  23

 **Outer Join**  &nbsp;  using  &nbsp; `merge`:

In [83]:
pd.merge(df1, df2, on='id', how='outer')

id    X1    X2    X3    X4    X5
0   1   2.0  10.0  22.0  52.0  22.0
1   2   4.0  12.0  33.0  -5.0  23.0
2   3   3.0   3.0   1.0   2.0  34.0
3   4  35.0   3.0   5.0   NaN   NaN
4   5  23.0 -13.0  -3.0   NaN   NaN
5   6   NaN   NaN   NaN  23.0  13.0
6   7   NaN   NaN   NaN   6.0  35.0

 **Inner Join**  &nbsp;  using  &nbsp; `merge`:

In [84]:
pd.merge(df1, df2, on='id', how='inner')


id  X1  X2  X3  X4  X5
0   1   2  10  22  52  22
1   2   4  12  33  -5  23
2   3   3   3   1   2  34

 **Left Join**  &nbsp;  using  &nbsp; `merge`:

In [85]:
pd.merge(df1, df2, on='id', how='left')

id  X1  X2  X3    X4    X5
0   1   2  10  22  52.0  22.0
1   2   4  12  33  -5.0  23.0
2   3   3   3   1   2.0  34.0
3   4  35   3   5   NaN   NaN
4   5  23 -13  -3   NaN   NaN

In [86]:
df1[['id']]

id
0   1
1   2
2   3
3   4
4   5

 **Right Join**  &nbsp;  using  &nbsp; `merge`:

In [87]:
pd.merge(df1, df2, on='id', how='right')

id   X1    X2    X3  X4  X5
0   1  2.0  10.0  22.0  52  22
1   3  3.0   3.0   1.0   2  34
2   6  NaN   NaN   NaN  23  13
3   7  NaN   NaN   NaN   6  35
4   2  4.0  12.0  33.0  -5  23

In [88]:
df2[['id']]

id
0   1
1   3
2   6
3   7
4   2

We could do all these joins even when the link columns would have different names:

In [89]:
df1 = pd.DataFrame( {"id1": id1 , "X1": X1 , "X2": X2 , "X3": X3 } ) 

df2 = pd.DataFrame( {"id2": id2 ,  "X4": X4 , "X5": X5  } ) 

For example, we can apply the outer join in this contest as follows:

In [90]:
pd.merge(df1, df2,  left_on='id1' , right_on='id2' , how='outer')

id1    X1    X2    X3  id2    X4    X5
0  1.0   2.0  10.0  22.0  1.0  52.0  22.0
1  2.0   4.0  12.0  33.0  2.0  -5.0  23.0
2  3.0   3.0   3.0   1.0  3.0   2.0  34.0
3  4.0  35.0   3.0   5.0  NaN   NaN   NaN
4  5.0  23.0 -13.0  -3.0  NaN   NaN   NaN
5  NaN   NaN   NaN   NaN  6.0  23.0  13.0
6  NaN   NaN   NaN   NaN  7.0   6.0  35.0

### Rename Columns <a class="anchor" id="17"></a>

In [91]:
df

Sex  X2  X3  X4
0  Masculino  10  22  15
1   Femenino  12   7  22
2  Masculino  32  40   5
3  Masculino  30  16 -30
4   Femenino -13  45  23

In [92]:
df.columns = [ 'a' , 'b' , 'c', 'd']

In [93]:
df

a   b   c   d
0  Masculino  10  22  15
1   Femenino  12   7  22
2  Masculino  32  40   5
3  Masculino  30  16 -30
4   Femenino -13  45  23

### Rename Rows <a class="anchor" id="18"></a>

In [94]:
df.index = [ 'r1' , 'r2' , 'r3', 'r4' , 'r5']

In [95]:
df

a   b   c   d
r1  Masculino  10  22  15
r2   Femenino  12   7  22
r3  Masculino  32  40   5
r4  Masculino  30  16 -30
r5   Femenino -13  45  23

Other way to do that:

In [96]:
df['index'] = [ 'a1' , 'a2' , 'a3' , 'a4' , 'a5']

In [97]:
df.set_index('index')

a   b   c   d
index                       
a1     Masculino  10  22  15
a2      Femenino  12   7  22
a3     Masculino  32  40   5
a4     Masculino  30  16 -30
a5      Femenino -13  45  23

## Numeric Sequencies <a class="anchor" id="19"></a>

In [98]:
repeat_unos = arr.array('i',(1 for i in range(0,15)))
repeat_unos

array('i', [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [99]:
list(range(4))

[0, 1, 2, 3]

In [133]:
np.array(range(4))

array([0, 1, 2, 3])

In [100]:
list(range(2,10)) # equivalente a 2:9 en R

[2, 3, 4, 5, 6, 7, 8, 9]

In [132]:
np.array(range(2,10))

array([2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
list(range(0, 10, 3)) # del 0 al 9 con saltos de 3 unidades

[0, 3, 6, 9]

In [131]:
np.array(range(0, 10, 3))

array([0, 3, 6, 9])

In [102]:
list(range(0, 10, 4)) # del 0 al 9 con saltos de 4 unidades

[0, 4, 8]

In [103]:
np.array(range(0, 10, 4))

array([0, 4, 8])

In [104]:
np.random.random_integers(0,10, size=25)

array([ 2,  8,  8,  6,  9,  7,  6,  9,  6, 10,  2,  0,  9,  9,  1,  8,  6,
        4,  5,  0,  9,  2, 10,  6,  3])

In [105]:
np.random.randn(25)

array([-1.16602801, -0.29126619,  0.0448093 , -1.53064805, -0.77986426,
        0.27946259,  0.70557339,  1.8947552 , -1.27201557, -2.38266208,
       -0.01028826,  0.48448163,  0.19373876,  0.51062877,  0.82499295,
       -1.2261926 , -0.64026091, -1.34130035,  0.72050095, -0.28182476,
       -1.41238308,  0.27093805,  0.12293903, -1.7454195 ,  0.59769211])

In [106]:
from random import uniform

np.round(np.random.uniform(3,10, 25))

array([ 7.,  7.,  7., 10.,  5.,  6.,  6.,  7.,  8.,  8.,  9.,  7.,  4.,
        8.,  4.,  5.,  9.,  3.,  9.,  8.,  6.,  5.,  7.,  3.,  5.])

In [107]:
set=np.random.uniform(3,10, 25)
set

array([4.38980167, 5.01942705, 8.37021446, 9.42328139, 5.23363136,
       6.7893964 , 7.0109037 , 4.19368942, 4.15756273, 8.35902992,
       5.12349693, 9.11500802, 8.33674298, 4.81632377, 5.75544898,
       4.69384069, 3.74076656, 9.63161338, 8.42379325, 9.56909962,
       5.34208547, 6.15814084, 7.27295296, 9.98284627, 9.96300636])

In [108]:
np.random.choice(set, 10) # sample(population, k)

array([7.27295296, 9.96300636, 5.01942705, 9.63161338, 5.12349693,
       5.23363136, 9.96300636, 4.81632377, 5.75544898, 4.69384069])

## Functions and loops <a class="anchor" id="20"></a>

### Functions :

In [109]:
def my_function(a, b):
    """
    a: numero
    b: numero
    """
    return 2*a + b


In [110]:
my_function(10, 1)

21

In [111]:
def my_function_2(a, b, c):
    
    return 2*a, b, 100+c

In [112]:
my_function_2(10, 2, 5)

(20, 2, 105)

### Loop If :

In [113]:
range(10)

range(0, 10)

In [114]:
x = 99

if x < 0:
    print(x, 'es negativo')
elif x > 0:   # elif = else if
    print(x, 'es positivo')
else:
    print('Pues será 0')

99 es positivo


### Loop For :

In [115]:
for i in range(10):
    if i - 2 > 4 :
        print(i)

7
8
9


In [116]:
for i in range(1, 5):
    if i == 3:
        break
    print(i)

1
2


In [117]:
for i in [1,2,3,4]:
    if i == 3:
        continue
    print(i)

1
2
4


### Loop While :

In [118]:
i = 0
x = True

while x == True:
    i += 1
    if(i == 4):
        x = False

print(i)

4


Let´s see how the  `+=` operator works in python:

In [119]:
i = 2

i += 5

i

7

There is also the `-=` operator in python:

In [120]:
i = 6

i -= 3

i

3

## Brief view of matrix with Numpy <a class="anchor" id="21"></a>

In [121]:
import numpy as np

In [122]:
B = np.matrix([[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]])
B

matrix([[ 1,  4,  5, 12],
        [-5,  8,  9,  0],
        [-6,  7, 11, 19]])

In [123]:
B[0]

matrix([[ 1,  4,  5, 12]])

In [124]:
B[2]

matrix([[-6,  7, 11, 19]])

In [125]:
B[:,0]

matrix([[ 1],
        [-5],
        [-6]])

In [126]:
B[: , 2]

matrix([[ 5],
        [ 9],
        [11]])

In [127]:
B[0,1]

4

In [128]:
B[1,2]

9

In [129]:
B[0,1] = 7
B

matrix([[ 1,  7,  5, 12],
        [-5,  8,  9,  0],
        [-6,  7, 11, 19]])

In [130]:
 A = np.zeros((3,3))
 A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])